import { MANAGEMENT_API_ZONE } from '@/api/PlatformZones'
import type { IKinotic, IServiceProxy } from '@kinotic-ai/core'
import type { ProjectSbom } from '@/api/model/deployment/ProjectSbom'

/**
 * The SBOMs of the caller's organization's projects, generated by the last step of every
 * deployment whose dependencies changed and kept in the organization's storage.
 */
export interface IProjectSbomService {

    /**
     * Finds the SBOM of one of the caller's organization's projects.
     * @param projectId a project belonging to the caller's organization
     * @return Promise emitting the SBOM, or null when the project's deployments have not generated one
     */
    findSbom(projectId: string): Promise<ProjectSbom | null>

    /**
     * Finds a URL the CycloneDX JSON document of a project's SBOM can be read from for the next
     * fifteen minutes, by anyone holding it.
     * @param projectId a project belonging to the caller's organization
     * @return Promise emitting the URL, or null when the project has no SBOM
     */
    findDocumentUrl(projectId: string): Promise<string | null>

}

export class ProjectSbomService implements IProjectSbomService {

    private readonly serviceProxy: IServiceProxy

    constructor(kinotic: IKinotic) {
        this.serviceProxy = kinotic.serviceProxy(`${MANAGEMENT_API_ZONE}~org.kinotic.management.api.services.deployment.ProjectSbomService`)
    }

    public findSbom(projectId: string): Promise<ProjectSbom | null> {
        return this.serviceProxy.invoke('findSbom', [projectId])
    }

    public findDocumentUrl(projectId: string): Promise<string | null> {
        return this.serviceProxy.invoke('findDocumentUrl', [projectId])
    }

}
