import { AutoGeneratedId, Entity, MultiTenancyType, NotIndexed } from "@kinotic/structures-api"
import type { DataInsightsComponent } from "@kinotic/structures-api"

@Entity(MultiTenancyType.SHARED)
export class DataInsightsWidget {
    @AutoGeneratedId
    public id: string | null = null
    public applicationId!: string
    @NotIndexed
    public dataInsightsComponent!: DataInsightsComponent
    public dashboardId?: string // Optional reference to dashboard
    public created!: Date
    public updated!: Date
}