# Headless service for Ignite node discovery in Kubernetes.
apiVersion: v1
kind: Service
metadata:
  name: kinotic
  labels:
    app: {{ include "kinotic.name" . }}
    component: ignite-discovery
spec:
  clusterIP: None
  selector:
    app: {{ include "kinotic.name" . }}
  ports:
    - name: discovery
      port: {{ .Values.kinotic.cluster.discoveryPort | default 47500 }}
      targetPort: {{ .Values.kinotic.cluster.discoveryPort | default 47500 }}
      protocol: TCP
    - name: communication
      port: {{ .Values.kinotic.cluster.communicationPort | default 47100 }}
      targetPort: {{ .Values.kinotic.cluster.communicationPort | default 47100 }}
      protocol: TCP
  publishNotReadyAddresses: true
