apiVersion: v1
kind: Service
metadata:
  name: {{ include "kinotic-server.fullname" . }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  {{- if eq (.Values.service.type | default "ClusterIP") "LoadBalancer" }}
  externalTrafficPolicy: Local
  {{- end }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours
  ports:
    - name: "ui"
      protocol: TCP
      port:  {{ .Values.properties.structures.webServerPort| default 9090 }}
      targetPort: {{ .Values.properties.structures.webServerPort| default 9090 }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.ui }}
      nodePort: {{ .Values.service.nodePorts.ui }}
      {{- end }}
    - name: "graph-ql"
      protocol: TCP
      port: {{ .Values.properties.structures.graphqlPort }}
      targetPort: {{ .Values.properties.structures.graphqlPort }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.graphql }}
      nodePort: {{ .Values.service.nodePorts.graphql }}
      {{- end }}
    - name: "open-api"
      protocol: TCP
      port: {{ .Values.properties.structures.openApiPort }}
      targetPort: {{ .Values.properties.structures.openApiPort }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.openApi }}
      nodePort: {{ .Values.service.nodePorts.openApi }}
      {{- end }}
    - name: "stomp"
      protocol: TCP
      port: {{ .Values.continuum_gateway.stomp.port| default 58503 }}
      targetPort: {{ .Values.continuum_gateway.stomp.port| default 58503 }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.stomp }}
      nodePort: {{ .Values.service.nodePorts.stomp }}
      {{- end }}
    - name: "rest"
      protocol: TCP
      port: 58504
      targetPort: 58504
  selector:
    app: {{ include "kinotic-server.name" . }}
