apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kinotic.fullname" . }}
  labels:
    app.kubernetes.io/part-of: {{ include "kinotic.name" . }}
  {{- if .Values.workloadIdentity.enabled }}
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.clientId | quote }}
  {{- end }}
