// Generates tokens/kinotic-theme.css for the Claude Design project from KinoticPreset,
// the same PrimeVue preset createKinoticApp installs.
//
// Run from kinotic-frontend: node .design-sync/generate-tokens.mjs
import { registerHooks, createRequire } from 'node:module'
import { existsSync, mkdirSync, realpathSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const commonDir = resolve(here, '../packages/common')
const outFile = resolve(here, 'out/tokens/kinotic-theme.css')

// The theme sources use extensionless relative imports, which Node's ESM resolver rejects.
registerHooks({
    resolve(specifier, context, nextResolve) {
        let ret
        if (specifier.startsWith('.') && context.parentURL?.endsWith('.ts') && !/\.\w+$/.test(specifier)) {
            const base = fileURLToPath(new URL(specifier, context.parentURL))
            const file = existsSync(base + '.ts') ? base + '.ts' : resolve(base, 'index.ts')
            ret = nextResolve(pathToFileURL(file).href, context)
        } else {
            ret = nextResolve(specifier, context)
        }
        return ret
    }
})

// Resolve @primeuix/styled through @primeuix/themes so both share one Theme singleton.
const themesRequire = createRequire(realpathSync(resolve(commonDir, 'node_modules/@primeuix/themes/package.json')))
const { Theme } = await import(pathToFileURL(themesRequire.resolve('@primeuix/styled')).href)
const { KinoticPreset } = await import(pathToFileURL(resolve(commonDir, 'src/KinoticPreset.ts')).href)

// Same options as createKinoticApp, except the dark selector also matches the project's
// existing [data-theme="dark"] convention.
Theme.setTheme({
    preset: KinoticPreset,
    options: { prefix: 'p', darkModeSelector: '.dark', cssLayer: false }
})

const blocks = []
const common = Theme.getCommon('common', {})
blocks.push(common.primitive.css, common.semantic.css, common.global.css)
for (const name of Object.keys(KinoticPreset.components ?? {})) {
    blocks.push(Theme.getComponent(name, {}).css)
}

// Parse "selector { --var: value; ... }" rules into mode -> Map(name -> value).
const modes = { light: new Map(), dark: new Map() }
for (const css of blocks.filter(Boolean)) {
    for (const [, selector, body] of css.matchAll(/([^{}]+)\{([^{}]*)\}/g)) {
        const mode = selector.includes('.dark') ? modes.dark : modes.light
        for (const [, name, value] of body.matchAll(/--p-([\w-]+)\s*:\s*([^;]+);/g)) {
            mode.set(name, value.trim().replaceAll('var(--p-', 'var(--'))
        }
    }
}

// The project's hand-written components multiply dimension tokens by 1px (unitless Figma floats),
// so only colour tokens are emitted; a dimension in rem would break those calc() expressions.
const all = new Map([...modes.light, ...modes.dark])
const kindCache = new Map()
function isColor(name, seen = new Set()) {
    if (kindCache.has(name)) return kindCache.get(name)
    const value = all.get(name)
    let ret
    if (value === undefined || seen.has(name)) {
        ret = false
    } else {
        seen.add(name)
        const ref = value.match(/^var\(--([\w-]+)\)$/)
        if (ref) {
            ret = isColor(ref[1], seen)
        } else {
            ret = /^(#[0-9a-f]{3,8}|rgba?\(|hsla?\(|color-mix\(|transparent$)/i.test(value)
        }
    }
    kindCache.set(name, ret)
    return ret
}

const render = (map) => [...map].filter(([name]) => isColor(name)).sort(([a], [b]) => a.localeCompare(b))
    .map(([name, value]) => `  --${name}: ${value};`).join('\n')

const css = `/* Generated by kinotic-frontend/.design-sync/generate-tokens.mjs from KinoticPreset.
   Colour tokens only, with PrimeVue's --p- prefix removed so they override the matching
   names in fig-tokens.css. Do not edit by hand — rerun the generator. */

:root {
${render(modes.light)}
}

:root[data-theme="dark"], .dark {
${render(modes.dark)}
}
`
mkdirSync(dirname(outFile), { recursive: true })
writeFileSync(outFile, css)
console.log(`wrote ${outFile}: ${render(modes.light).split('\n').length} light, ${render(modes.dark).split('\n').length} dark`)
