
# YAML Reference http://www.yaml.org/refcard.html
kinotic:
  debug: true
  maxNumberOfCoresToUse: 4
  ignite:
    discoveryType: SHAREDFS
  persistence:
    corsAllowedOriginPattern: "https:\\/\\/studio.apollographql.com|http:\\/\\/localhost:\\d+|http:\\/\\/121.0.0.1:\\d+"
    corsAllowedHeaders:
      - "*"
    corsAllowCredentials: true
    elastic-connections:
      - scheme: "http"
        host: "localhost"
        port: "9200"

logging:
  level:
    org:
      kinotic: TRACE
#    io:
#      vertx: WARN
#      netty:
#        util: DEBUG
#        buffer: DEBUG

spring:
  ai:
    openai:
      api-key: "noop"
      base-url: https://api.x.ai
      chat:
        options:
          model: grok-4


# OIDC security service configuration
# oidc-security-service:
#   enabled: false
#   debug: false
