import { join } from 'node:path'
import { SYSTEM_LOG_TENANT } from '@kinotic-ai/os-api'
import type { LogTarget } from '@/model/LogTarget'

export interface AlloyConfigOptions {
    /** Base URL of the Loki HTTP API (e.g. http://localhost:3100). */
    lokiUrl: string
    /** This vm-manager node's id, applied as the node_id label on every stream. */
    nodeId: string
}

/**
 * Renders the Alloy pipeline for the given log targets: one file source per running VM,
 * a shared process stage that routes each stream to its organization's Loki tenant, and
 * a single Loki write endpoint. Returns the complete config file content.
 */
export function generateAlloyConfig(targets: LogTarget[], options: AlloyConfigOptions): string {
    const sections: string[] = [
        '// Generated by vm-manager — do not edit. Regenerated as workloads come and go.',
        '',
        ...targets.map(target => renderTarget(target, options.nodeId)),
        `loki.process "workloads" {
  // The transient tenant label becomes X-Scope-OrgID on push and is never stored
  stage.tenant {
    source = "tenant"
  }
  stage.label_drop {
    values = ["tenant"]
  }
  forward_to = [loki.write.default.receiver]
}

loki.write "default" {
  endpoint {
    url = ${river(options.lokiUrl + '/loki/api/v1/push')}
  }
}
`,
    ]
    return sections.join('\n')
}

function renderTarget(target: LogTarget, nodeId: string): string {
    const name = componentName(target.workloadId)
    const labels = [
        `      __path__       = ${river(join(target.logDir, '*.log'))},`,
        `      workload_id    = ${river(target.workloadId)},`,
        `      vm_id          = ${river(target.vmId)},`,
        `      node_id        = ${river(nodeId)},`,
        ...(target.applicationId ? [`      application_id = ${river(target.applicationId)},`] : []),
        `      tenant         = ${river(target.organizationId ?? SYSTEM_LOG_TENANT)},`,
    ]
    return `local.file_match ${river(name)} {
  path_targets = [
    {
${labels.join('\n')}
    },
  ]
}

loki.source.file ${river(name)} {
  targets    = local.file_match.${name}.targets
  forward_to = [loki.process.workloads.receiver]
}
`
}

// Alloy component labels must match [A-Za-z_][A-Za-z0-9_]*; workload ids are UUIDs
function componentName(workloadId: string): string {
    return `wl_${workloadId.replace(/[^A-Za-z0-9_]/g, '_')}`
}

// River string literals use JSON-compatible escaping
function river(value: string): string {
    return JSON.stringify(value)
}
