package org.kinotic.persistence.internal.api.hooks.impl;

import org.kinotic.persistence.api.model.idl.decorators.AutoGeneratedIdDecorator;
import org.kinotic.persistence.internal.api.hooks.UpsertFieldPreProcessor;
import org.kinotic.persistence.api.model.EntityContext;
import org.kinotic.persistence.api.model.Structure;
import org.springframework.stereotype.Component;

import java.util.UUID;

/**
 * Created by Navíd Mitchell 🤪 on 5/9/23.
 */
@Component
public class AutoGeneratedIdUpsertFieldPreProcessor implements UpsertFieldPreProcessor<AutoGeneratedIdDecorator, String, String> {

    @Override
    public Class<AutoGeneratedIdDecorator> implementsDecorator() {
        return AutoGeneratedIdDecorator.class;
    }

    @Override
    public Class<String> supportsFieldType() {
        return String.class;
    }

    @Override
    public String process(Structure structure, String fieldName, AutoGeneratedIdDecorator decorator, String fieldValue, EntityContext context) {
        return fieldValue != null && !fieldValue.isBlank() ? fieldValue : UUID.randomUUID().toString();
    }
}
