package org.kinotic.persistence.internal.api.hooks.impl;

import io.opentelemetry.instrumentation.annotations.WithSpan;
import io.vertx.core.Future;
import org.apache.commons.lang3.tuple.Pair;
import org.kinotic.idl.api.schema.decorators.C3Decorator;
import org.kinotic.persistence.api.config.PersistenceProperties;
import org.kinotic.persistence.api.model.EntityDescriptor;
import org.kinotic.persistence.api.model.idl.decorators.AutoGeneratedIdDecorator;
import org.kinotic.persistence.api.model.idl.decorators.IdDecorator;
import org.kinotic.persistence.api.model.EntityContext;
import org.kinotic.persistence.api.model.idl.decorators.MultiTenancyType;
import org.kinotic.persistence.api.model.idl.decorators.VersionDecorator;
import org.kinotic.persistence.internal.api.hooks.DecoratorLogic;
import org.kinotic.persistence.internal.api.hooks.UpsertFieldPreProcessor;
import org.kinotic.persistence.internal.api.hooks.UpsertPreProcessor;
import org.kinotic.persistence.internal.api.services.EntityHolder;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Created by Navíd Mitchell 🤪 on 6/7/23.
 */
public class MapUpsertPreProcessor implements UpsertPreProcessor<Map<Object, Object>, List<Map<Object, Object>>, Map<Object, Object>> {

    private final EntityDescriptor entityDescriptor;
    private final PersistenceProperties persistenceProperties;
    private Pair<String, DecoratorLogic> idFieldPreProcessor = null;
    private String versionFieldName = null;

    public MapUpsertPreProcessor(EntityDescriptor entityDescriptor,
                                 PersistenceProperties persistenceProperties,
                                 Map<String, DecoratorLogic> fieldPreProcessors) {
        this.entityDescriptor = entityDescriptor;
        this.persistenceProperties = persistenceProperties;

        // this is a temporary solution since we only have an id and version field preprocessor now.
        for(Map.Entry<String, DecoratorLogic> entry : fieldPreProcessors.entrySet()) {
            C3Decorator decorator = entry.getValue().getDecorator();
            if(decorator instanceof IdDecorator
                    || decorator instanceof AutoGeneratedIdDecorator) {

                idFieldPreProcessor = Pair.of(entry.getKey(), entry.getValue());

            }else if(decorator instanceof VersionDecorator) {

                versionFieldName = entry.getKey();
            }
        }
    }

    @WithSpan
    @Override
    public Future<EntityHolder<Map<Object, Object>>> process(Map<Object, Object> entity,
                                                             EntityContext context) {
        try {
            // We always blow away tenant selection on save/update since the only tenants that mater are the ones in the data
            // This is a sanity check, in case somehow it was already provided. We want to make sure auth services see the correct list.
            if(entityDescriptor.isMultiTenantSelectionEnabled()){
                context.setTenantSelection(new ArrayList<>());
            }

            return Future.succeededFuture(preProcessData(entity, context));

        } catch (Exception e) {
            return Future.failedFuture(e);
        }
    }

    @WithSpan
    @Override
    public Future<List<EntityHolder<Map<Object, Object>>>> processArray(List<Map<Object, Object>> entities,
                                                                        EntityContext context) {
        try {
            // We always blow away tenant selection on save/update since the only tenants that mater are the ones in the data
            // This is a sanity check, in case somehow it was already provided. We want to make sure auth services see the correct list.
            if(entityDescriptor.isMultiTenantSelectionEnabled()){
                context.setTenantSelection(new ArrayList<>());
            }

            List<EntityHolder<Map<Object, Object>>> entityHolders = new ArrayList<>();
            for(Map<Object, Object> entity : entities) {
                entityHolders.add(preProcessData(entity, context));
            }
            return Future.succeededFuture(entityHolders);
        } catch (Exception e) {
            return Future.failedFuture(e);
        }
    }

    private EntityHolder<Map<Object, Object>> preProcessData(Map<Object, Object> entity, EntityContext context) {
        String tenantId;
        String idFieldName = idFieldPreProcessor.getLeft();
        Object idFieldValue = entity.get(idFieldName);
        DecoratorLogic decoratorLogic = idFieldPreProcessor.getRight();
        C3Decorator decorator = decoratorLogic.getDecorator();
        UpsertFieldPreProcessor<C3Decorator, Object, Object> preProcessor = decoratorLogic.getProcessor();

        // we know this is the IdDecorator, so we can cast it
        String id = (String) preProcessor.process(idFieldName, decorator, idFieldValue, context);

        // make sure the id is not null before appending to it
        if(id == null || id.isBlank()){
            throw new IllegalArgumentException("Could not find id for Entity");
        }

        // we just always put the id back into the entity to simplify the logic
        entity.put(idFieldName, id);

        // now verify the tenant id is set properly
        if(entityDescriptor.multiTenancyType() == MultiTenancyType.SHARED){

            if(entityDescriptor.isMultiTenantSelectionEnabled()){

                tenantId = (String) entity.get(entityDescriptor.tenantIdFieldName());
                if(tenantId == null){
                    throw new IllegalArgumentException("Could not find TenantId for Entity");
                }

                context.getTenantSelection().add(tenantId);

            } else {

                tenantId = (String) entity.get(persistenceProperties.getTenantIdFieldName());

                if (tenantId != null && !tenantId.equals(context.getTenantId())) {
                    throw new IllegalArgumentException("Tenant Id invalid for logged in participant");

                } else if (tenantId == null) {
                    tenantId = context.getTenantId();
                    entity.put(persistenceProperties.getTenantIdFieldName(), tenantId);
                }
            }
        }else {
            tenantId = null;
        }

        // now extract version field if expected
        String version = null;
        if(entityDescriptor.isOptimisticLockingEnabled()) {
            if(entity.containsKey(versionFieldName)) {
                version = (String) entity.get(versionFieldName);
                entity.remove(versionFieldName);
            }
        }

        return new EntityHolder<>(entity,
                                  id,
                                  entityDescriptor.multiTenancyType(),
                                  tenantId,
                                  version
        );
    }
}
