import { IEntitiesService } from '@kinotic-ai/persistence'
import { BasePersonEntityService } from './generated/BasePersonEntityService.js'

/**
 * Service for interacting with Person entities
 * This class was generated by the structures cli
 */
export class PersonEntityService extends BasePersonEntityService {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
