kinoticVersion=4.2.0-SNAPSHOT

org.gradle.caching=true
org.gradle.parallel=true

allureVersion=2.33.0
antlrVersion=4.13.2
apacheCommonsCompressVersion=1.27.1
apacheCommonsLangVersion=3.20.0
apacheCommonsTextVersion=1.15.0
aspectJVersion=1.9.25.1
azureCommunicationEmailVersion=1.1.2
azureIdentityVersion=1.18.2
azureKeyvaultSecretsVersion=4.9.2
caffeineVersion=3.1.8
chronicleMapVersion=3.27ea2
commonsIoVersion=2.21.0
elasticClientVersion=9.2.4
failsafeVersion=3.3.2
graalvmPolyglotVersion=25.0.1
graphQlFederationJvmVersion=5.3.0
graphQlJavaExtendedScalarsVersion=22.0
graphQlJavaVersion=22.3
groovyVersion=4.0.26
handlebarsVersion=4.5.1
igniteVersion=2.18.0
jakartaAnnotationVersion=3.0.0
jakartaJsonVersion=2.0.1
jCacheApiVersion=1.0.0
jreleaserVersion=1.24.0
jsonwebtokenVersion=0.12.6
kinoticSpawnVersion=0.5.0
lombokPluginVersion=9.2.0
luceneVersion=8.11.4
mcpSdkVersion=2.0.0
otelBomVersion=1.57.0
otelInstrumentationBomVersion=2.24.0
slugifyVersion=3.0.7
springAiVersion=1.1.2
springBootVersion=4.0.7
springDependencyManagementVersion=1.1.7
swaggerCoreVersion=2.2.27
testcontainersBomVersion=1.21.3
testcontainersKeycloakVersion=3.8.0
testContainersVersion=2.0.3
vertxStompLiteVersion=6.0.0
vertxVersion=5.1.4
