import {AutoGeneratedId, Entity, MultiTenancyType, Precision, PrecisionType, Discriminator, NotIndexed} from '@kinotic-ai/persistence'
import {Address} from './Address.js'
import type {Pet} from './Pet.js'

@Entity(MultiTenancyType.SHARED)
export class Person {
    @AutoGeneratedId
    public id: string | null = null
    public firstName: string = ''

    public lastName: string = ''

    @Precision(PrecisionType.SHORT)
    public age?: number

    public address!: Address

    @Discriminator('type')
    public myPet?: Pet

    @NotIndexed
    public favoriteSaying!: string

}
