plugins {
	id 'org.kinotic.server-conventions'
}

dependencies {
	implementation project(':kinotic-core')
	implementation project(':kinotic-domain')
	implementation project(':kinotic-persistence')
	implementation project(':kinotic-api-gateway')
	implementation project(':kinotic-authz')

	implementation 'io.vertx:vertx-core'
	implementation 'io.vertx:vertx-web'

	implementation 'org.springframework.boot:spring-boot-starter-validation'
}
