import { AutoGeneratedId, Entity, MultiTenancyType } from "@kinotic-ai/persistence"

export class DashboardWidget {
    public id: string | null = null
    public dashboardId!: string
    public widgetId!: string // Reference to the DataInsightsWidget
    public x!: number
    public y!: number
    public w!: number
    public h!: number
    public minW?: number
    public minH?: number
    public maxW?: number
    public maxH?: number
    public locked?: boolean
    public noResize?: boolean
    public noMove?: boolean
    public static_?: boolean
    public created!: Date
    public updated!: Date
}

// Explicit registration calls instead of decorator syntax: the persistence
// decorators are legacy (experimentalDecorators) style, which Oxc-based Vite
// versions don't transpile.
Entity(MultiTenancyType.SHARED)(DashboardWidget)
AutoGeneratedId(DashboardWidget.prototype, 'id')
