import { AutoGeneratedId, Entity, MultiTenancyType, NotIndexed } from "@kinotic-ai/persistence"

export class Dashboard {
    public id: string | null = null
    public name!: string
    public description: string | null = null
    public applicationId!: string
    public layout!: string
    public created!: Date
    public updated!: Date
}

// Explicit registration calls instead of decorator syntax: the persistence
// decorators are legacy (experimentalDecorators) style, which Oxc-based Vite
// versions don't transpile.
Entity(MultiTenancyType.SHARED)(Dashboard)
AutoGeneratedId(Dashboard.prototype, 'id')
NotIndexed(Dashboard.prototype, 'layout')
