import type {DataInsightsComponent} from './DataInsightsComponent.js'
import { AutoGeneratedId, Entity, MultiTenancyType, NotIndexed } from "@kinotic-ai/persistence"

export class DataInsightsWidget {
    public id: string | null = null
    public applicationId!: string
    public dataInsightsComponent!: DataInsightsComponent
    public dashboardId?: string // Optional reference to dashboard
    public created!: Date
    public updated!: Date
}

// Explicit registration calls instead of decorator syntax: the persistence
// decorators are legacy (experimentalDecorators) style, which Oxc-based Vite
// versions don't transpile.
Entity(MultiTenancyType.SHARED)(DataInsightsWidget)
AutoGeneratedId(DataInsightsWidget.prototype, 'id')
NotIndexed(DataInsightsWidget.prototype, 'dataInsightsComponent')
