package org.kinotic.persistence.api.domain.idl.decorators;

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.kinotic.idl.api.schema.decorators.C3Decorator;
import org.kinotic.idl.api.schema.decorators.DecoratorTarget;

import java.util.List;

/**
 * Created by Navíd Mitchell 🤪on 6/24/23.
 */
public final class AutoGeneratedIdDecorator extends C3Decorator {

    @JsonIgnore
    public static final String type = "AutoGeneratedId";

    public AutoGeneratedIdDecorator(){
        this.targets = List.of(DecoratorTarget.FIELD);
    }
}
