include:
  - compose.elasticsearch.yml
  - compose.kibana.yml
  - compose-otel.yml
  - compose.gen-schemas.yml
  - path: compose.kinotic-migration.yml
    env_file: evaluation.env
  - compose.kinotic-servers.yml
