import {
    AuthzCheckDecorator,
    AuthzResourceDecorator,
    AuthzRoleDeclaration,
    C3Decorator,
    C3Type,
    DoubleC3Type,
    FloatC3Type,
    IntC3Type,
    LongC3Type,
    NotNullDecorator, ShortC3Type
} from '@kinotic-ai/idl'
import {
    AutoGeneratedIdDecorator,
    DiscriminatorDecorator,
    EntityDecorator,
    EsIndexConfigurationDecorator,
    FlattenedDecorator,
    IdDecorator,
    NestedDecorator,
    NotIndexedDecorator,
    QueryDecorator,
    TenantIdDecorator,
    TextDecorator,
    TimeReferenceDecorator,
    VersionDecorator
} from '@kinotic-ai/management-api'
import {
    EsIndexConfigurationData,
    EntityType,
    MultiTenancyType
} from '@kinotic-ai/persistence'
import {Decorator, SyntaxKind, ObjectLiteralExpression} from 'ts-morph'

export function tsDecoratorToC3Decorator(decorator: Decorator): C3Decorator | null {
    let ret: C3Decorator | null = null

    if (decorator.getName() === 'AutoGeneratedId') {
        ret = new AutoGeneratedIdDecorator()
    } else if (decorator.getName() === 'AuthzCheck') {
        ret = authzCheckDecorator(decorator)
    } else if (decorator.getName() === 'AuthzUnchecked') {
        const unchecked = new AuthzCheckDecorator()
        unchecked.unchecked = true
        ret = unchecked
    } else if (decorator.getName() === 'AuthzResource') {
        ret = authzResourceDecorator(decorator)
    } else if (decorator.getName() === 'Discriminator') {
        const discriminatorDecorator = new DiscriminatorDecorator()
        if (decorator.getArguments().length == 1) {
            const argument = decorator.getArguments()[0]
            if (argument?.getType()?.getLiteralValue()) {
                discriminatorDecorator.propertyName = argument.getType().getLiteralValue() as string
            } else {
                throw new Error('propertyName must be a string literal')
            }
        }else{
            throw new Error('propertyName must be set on Discriminator Decorator')
        }
        ret = discriminatorDecorator
    } else if (decorator.getName() === 'Entity') {
        const entityDecorator = new EntityDecorator()
        if (decorator.getArguments().length > 0) {
            const argument = decorator.getArguments()[0]
            if (argument?.getText() == 'MultiTenancyType.SHARED') {
                entityDecorator.multiTenancyType = MultiTenancyType.SHARED
            } else if (argument?.getText() == 'MultiTenancyType.NONE') {
                entityDecorator.multiTenancyType = MultiTenancyType.NONE
            } else {
                throw new Error(`Unsupported MultiTenancyType ${argument?.getText()}`)
            }

            if(decorator.getArguments().length == 2){
                const entityTypeArg = decorator.getArguments()[1]
                if (entityTypeArg?.getText() == 'EntityType.TABLE') {
                    entityDecorator.entityType = EntityType.TABLE
                } else if (entityTypeArg?.getText() == 'EntityType.STREAM') {
                    entityDecorator.entityType = EntityType.STREAM
                } else {
                    throw new Error(`Unsupported EntityType ${entityTypeArg?.getText()}`)
                }
            }
        }
        ret = entityDecorator
    } else if (decorator.getName() === 'EsIndexConfiguration') {
        const argument = decorator.getArguments()[0]
        if (argument?.getKind() === SyntaxKind.ObjectLiteralExpression) {
            const obj = convertToObjectLiteral(argument as ObjectLiteralExpression)
            ret = {
                type  : 'EsIndexConfigurationDecorator',
                value: obj as EsIndexConfigurationData,
            } as EsIndexConfigurationDecorator
        } else {
            throw new Error('EsIndexConfiguration must have an object literal argument')
        }
    } else if (decorator.getName() === 'Flattened') {
        ret = new FlattenedDecorator()
    } else if (decorator.getName() === 'Id') {
        ret = new IdDecorator()
    } else if (decorator.getName() === 'Nested') {
        ret = new NestedDecorator()
    } else if (decorator.getName() === 'NotIndexed') {
        ret = new NotIndexedDecorator()
    } else if (decorator.getName() === 'NotNull') {
        ret = new NotNullDecorator()
    } else if (decorator.getName() === 'Query') {
        if (decorator.getArguments().length == 1) {
            const argument = decorator.getArguments()[0]
            if (argument?.getType()?.getLiteralValue()) {
                ret = new QueryDecorator(argument.getType().getLiteralValue() as string)
            } else {
                throw new Error('statement must be set on Query Decorator')
            }
        }
    } else if (decorator.getName() === 'TenantId') {
        ret = new TenantIdDecorator()
    } else if (decorator.getName() === 'Text') {
        ret = new TextDecorator()
    } else if (decorator.getName() === 'TimeReference') {
        ret = new TimeReferenceDecorator()
    } else if (decorator.getName() === 'Version') {
        ret = new VersionDecorator()
    }

    return ret
}


export function convertPrecisionToC3Type(decorator: Decorator): C3Type {
    let ret: C3Type
    if(decorator.getName() === 'Precision'){
        if (decorator.getArguments().length == 1) {
            const argument = decorator.getArguments()[0]
            if (argument?.getText() == 'PrecisionType.DOUBLE') {
                ret = new DoubleC3Type()
            } else if (argument?.getText() == 'PrecisionType.FLOAT') {
                ret = new FloatC3Type()
            } else if (argument?.getText() == 'PrecisionType.INT') {
                ret = new IntC3Type()
            } else if (argument?.getText() == 'PrecisionType.LONG') {
                ret = new LongC3Type()
            } else if (argument?.getText() == 'PrecisionType.SHORT') {
                ret = new ShortC3Type()
            } else {
                throw new Error(`Unsupported PrecisionType ${argument?.getText()}`)
            }
        }else{
            ret = new IntC3Type()
        }
        return ret
    }else{
        throw new Error('Decorator is not Precision decorator')
    }
}

// @AuthzResource('report') or @AuthzResource({value, parent, objectId, permission, roles}), as the runtime's
// decorator declares it
function authzResourceDecorator(decorator: Decorator): AuthzResourceDecorator {
    const argument = decorator.getArguments()[0]
    if (!argument) {
        throw new Error('AuthzResource must name the resource type')
    }
    const declaration = parseExpressionToJs(argument)
    const declared = typeof declaration === 'string' ? {value: declaration} : declaration
    if (typeof declared?.value !== 'string' || declared.value.length === 0) {
        throw new Error('AuthzResource must name the resource type')
    }
    const ret = new AuthzResourceDecorator(declared.value)
    ret.parent = declared.parent ?? null
    ret.objectId = declared.objectId ?? null
    ret.permission = declared.permission ?? null
    ret.roles = (declared.roles ?? []).map((role: any) => new AuthzRoleDeclaration(role.id, role.permissions ?? []))
    return ret
}

// @AuthzCheck({permission, resource, objectId, implies, consistent}), as the runtime's decorator declares it
function authzCheckDecorator(decorator: Decorator): AuthzCheckDecorator {
    const argument = decorator.getArguments()[0]
    if (!argument) {
        throw new Error('AuthzCheck must declare what the derivation cannot read')
    }
    const declared = parseExpressionToJs(argument)
    const ret = new AuthzCheckDecorator()
    ret.permission = declared.permission ?? null
    ret.resource = declared.resource ?? null
    ret.objectId = declared.objectId ?? null
    ret.implies = declared.implies ?? []
    ret.consistent = declared.consistent === true
    return ret
}

function parseExpressionToJs(expression: any): any {
    switch (expression.getKind()) {
        case SyntaxKind.AsExpression:
            // Directly handle the expression part of the AsExpression
            const asExpr = expression.asKindOrThrow(SyntaxKind.AsExpression)
            return parseExpressionToJs(asExpr.getExpression())
        case SyntaxKind.ObjectLiteralExpression:
            return convertToObjectLiteral(expression as ObjectLiteralExpression)
        case SyntaxKind.ArrayLiteralExpression:
            return expression.asKindOrThrow(SyntaxKind.ArrayLiteralExpression)
                             .getElements()
                             .map((el: any) => parseExpressionToJs(el))
        case SyntaxKind.StringLiteral:
            return expression.asKindOrThrow(SyntaxKind.StringLiteral).getLiteralValue()
        case SyntaxKind.NumericLiteral:
            return parseFloat(expression.asKindOrThrow(SyntaxKind.NumericLiteral).getLiteralText())
        case SyntaxKind.TrueKeyword:
            return true
        case SyntaxKind.FalseKeyword:
            return false
        default:
            throw new Error(`Unsupported expression kind: ${expression.getKindName()} text: ${expression.getText()}`)
    }
}

// Convert ObjectLiteralExpression to a JavaScript object
function convertToObjectLiteral(expression: ObjectLiteralExpression): any {
    const result: any = {}
    for(const prop of expression.getProperties()) {
        if (prop.getKind() === SyntaxKind.PropertyAssignment) {
            const assignment = prop.asKindOrThrow(SyntaxKind.PropertyAssignment)
            const key = assignment.getName()
            const initializer = assignment.getInitializer()
            if (initializer) {
                result[key] = parseExpressionToJs(initializer)
            }
        }
    }
    return result
}
