apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.config.server.http_listen_port }}
      targetPort: http
    - name: grpc
      port: {{ .Values.config.server.grpc_listen_port }}
      targetPort: grpc
