plugins {
    id 'org.kinotic.java-library-conventions'
}

dependencies {
    implementation project(':kinotic-core')

    implementation 'com.azure:azure-communication-email'
    implementation 'com.azure:azure-identity'

    implementation 'io.vertx:vertx-auth-common'
    implementation 'io.vertx:vertx-auth-jwt'
    implementation 'io.vertx:vertx-auth-oauth2'
    implementation 'io.vertx:vertx-core'
    implementation 'io.vertx:vertx-web'
    implementation 'io.vertx:vertx-web-client'

    implementation 'io.projectreactor:reactor-core'

    implementation 'co.elastic.clients:elasticsearch-java'
    implementation 'co.elastic.clients:elasticsearch-rest5-client'

    implementation 'org.apache.ignite:ignite-core'

    implementation 'io.jsonwebtoken:jjwt-api'
    runtimeOnly    'io.jsonwebtoken:jjwt-impl'
    runtimeOnly    'io.jsonwebtoken:jjwt-jackson'

    implementation 'com.github.ben-manes.caffeine:caffeine'

    implementation "com.github.slugify:slugify:${slugifyVersion}"

    implementation 'org.springframework:spring-core'
    implementation 'org.springframework:spring-context'
    implementation 'org.springframework.security:spring-security-crypto'
    implementation('com.github.jknack:handlebars') {
        // Nashorn is only used by handlebars for server-side JS precompilation, which we never do.
        exclude group: 'org.openjdk.nashorn', module: 'nashorn-core'
    }
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    implementation 'tools.jackson.core:jackson-core'
    implementation 'tools.jackson.core:jackson-databind'
}
