import { type IEntitiesRepository } from '@kinotic-ai/persistence'
import { BaseAlertRepository } from './generated/BaseAlertRepository.js'

/**
 * Repository for interacting with Alert entities
 * This class was generated by the Kinotic CLI
 */
export class AlertRepository extends BaseAlertRepository {

  constructor(entitiesRepository?: IEntitiesRepository) {
    super(false, entitiesRepository)
  }

}
