import { type IEntitiesRepository } from '@kinotic-ai/persistence'
import { BasePersonWithTenantRepository } from './generated/BasePersonWithTenantRepository.js'

/**
 * Repository for interacting with PersonWithTenant entities
 * This class was generated by the Kinotic CLI
 */
export class PersonWithTenantRepository extends BasePersonWithTenantRepository {

  constructor(entitiesRepository?: IEntitiesRepository) {
    super(false, entitiesRepository)
  }

}
