import { type IAdminEntitiesRepository } from '@kinotic-ai/persistence'
import { BasePersonWithTenantAdminRepository } from './generated/BasePersonWithTenantAdminRepository.js'

/**
 * Admin Repository for interacting with PersonWithTenant entities
 * This class was generated by the Kinotic CLI
 */
export class PersonWithTenantAdminRepository extends BasePersonWithTenantAdminRepository {

  constructor(adminEntitiesService?: IAdminEntitiesRepository) {
    super(adminEntitiesService)
  }

}
