import { type IEntitiesRepository } from '@kinotic-ai/persistence'
import { BasePersonRepository } from './generated/BasePersonRepository.js'

/**
 * Repository for interacting with Person entities
 * This class was generated by the Kinotic CLI
 */
export class PersonRepository extends BasePersonRepository {

  constructor(entitiesRepository?: IEntitiesRepository) {
    super(false, entitiesRepository)
  }

}
