import { IAdminEntitiesRepository, Query, type TenantSelection } from '@kinotic-ai/persistence'
import { BasePersonWithTenantAdminRepository } from './generated/BasePersonWithTenantAdminRepository.js'

export class CountResult {
  public count!: number
}

/**
 * Admin Repository for interacting with PersonWithTenant entities
 * This class was generated by the Kinotic CLI
 */
export class PersonWithTenantAdminRepository extends BasePersonWithTenantAdminRepository {

  constructor(adminEntitiesService?: IAdminEntitiesRepository) {
    super(adminEntitiesService)
  }

  /**
   * Get a count of all people in a given city
   * @param lastName to search for
   * @param tenantSelection to use
   */
  @Query('select count(firstName) as count from "kinotic_PLACEHOLDER" where lastName = ?')
  public async adminCountByLastName(lastName: string, tenantSelection: TenantSelection): Promise<CountResult[]> {
    /** Autogenerated code, changes will be overwritten. **/
    const parameters = [
      {key: 'lastName', value: lastName},
      {key: 'tenantSelection', value: tenantSelection}
    ]
    return this.namedQuery('adminCountByLastName', parameters)
  }

}
