import { type IEntitiesRepository } from '@kinotic-ai/persistence'
import { BaseVehicleRepository } from './generated/BaseVehicleRepository.js'

/**
 * Repository for interacting with Vehicle entities
 * This class was generated by the Kinotic CLI
 */
export class VehicleRepository extends BaseVehicleRepository {

  constructor(entitiesRepository?: IEntitiesRepository) {
    super(false, entitiesRepository)
  }

}
