import { type IEntitiesService } from '@kinotic-ai/persistence'
import { BaseDashboardWidgetEntityService } from './generated/BaseDashboardWidgetEntityService.js'

/**
 * Service for interacting with DashboardWidget entities
 * This class was generated by the structures cli
 */
export class DashboardWidgetEntityService extends BaseDashboardWidgetEntityService {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
