import { type IEntitiesRepository } from '@kinotic-ai/persistence'
import { BaseDashboardWidgetEntityRepository } from './generated/BaseDashboardWidgetEntityRepository.js'

/**
 * Repository for interacting with DashboardWidget entities
 * This class was generated by the structures cli
 */
export class DashboardWidgetEntityRepository extends BaseDashboardWidgetEntityRepository {

  constructor(entitiesRepository?: IEntitiesRepository) {
    super(false, entitiesRepository)
  }

}
