import { type IEntitiesRepository } from '@kinotic-ai/persistence'
import { BaseDashboardEntityRepository } from './generated/BaseDashboardEntityRepository.js'

/**
 * Repository for interacting with Dashboard entities
 * This class was generated by the structures cli
 */
export class DashboardEntityRepository extends BaseDashboardEntityRepository {

  constructor(entitiesRepository?: IEntitiesRepository) {
    super(false, entitiesRepository)
  }

}
