import { type IEntitiesRepository } from '@kinotic-ai/persistence'
import { Pageable } from '@kinotic-ai/core'
import { BaseDataInsightsWidgetEntityRepository } from './generated/BaseDataInsightsWidgetEntityRepository.js'
import { DataInsightsWidget } from '@/domain/DataInsightsWidget'

/**
 * Repository for interacting with DataInsightsWidget entities
 * This class was generated by the structures cli
 */
export class DataInsightsWidgetEntityRepository extends BaseDataInsightsWidgetEntityRepository {

  constructor(entitiesRepository?: IEntitiesRepository) {
    super(false, entitiesRepository)
  }

  async findByApplicationId(applicationId: string): Promise<DataInsightsWidget[]> {
    const pageable = Pageable.create(0, 1000)
    const result = await this.findAll(pageable)

    if (!result.content) {
      return []
    }

    const filtered = result.content.filter((widget: DataInsightsWidget) => {
      return widget.applicationId === applicationId
    })

    return filtered
  }

}
