

package org.kinotic.orchestrator.api.grind;

import org.kinotic.orchestrator.internal.api.grind.DefaultJobDefinition;

import java.util.List;

/**
 * A {@link JobDefinition} provides a unit of work comprised of {@link Task}'s and other {@link JobDefinition}
 * For every {@link JobDefinition} a {@link JobContext} is provided,
 * to allow {@link Task}'s to automatically store and access data produced by {@link Task}'s
 *
 * A {@link JobDefinition} is one run's worth of bound steps: its {@link Task} instances receive
 * injection per execution, so build a fresh definition for each run - executing the same instance
 * concurrently is not supported.
 *
 * Created by Navid Mitchell on 3/19/20
 */
public interface JobDefinition extends HasSteps{

    /**
     * @return the description of this {@link JobDefinition}
     */
    String getDescription();

    /**
     * The stable name identifying this job across runs, recorded with every execution.
     * Required by {@link JobService#execute(JobDefinition)}, optional for definitions
     * that are only nested within or assembled by others.
     * @return the name or null if none was set
     */
    String getName();

    /**
     * The version of this job's definition, recorded with every execution so a persisted
     * run can be matched to the code that produced it.
     * @return the version or null if none was set
     */
    String getVersion();

    /**
     * Sets the stable name identifying this job across runs.
     * @param name to use
     * @return this for fluent use
     */
    JobDefinition name(String name);

    /**
     * Sets the version of this job's definition.
     * @param version to use
     * @return this for fluent use
     */
    JobDefinition version(String version);

    /**
     * If this {@link JobDefinition} supports running it's  {@link Task}'s in parallel
     *
     * @return true if {@link Tasks}'s can be run in parallel false if not
     */
    boolean isParallel();

    /**
     * The {@link JobScope} that will be used during the execution of this  {@link JobDefinition}
     * @return the {@link JobScope} the default is {@link JobScope#CHILD}
     */
    JobScope getScope();

    /**
     * Adds a {@link Task} to the list of {@link Task}'s that will be executed by this {@link JobDefinition}
     * @param task to add
     * @return this for fluent use
     */
    JobDefinition task(Task<?> task);

    /**
     * Adds a {@link Task} to the list of {@link Task}'s that will be executed by this {@link JobDefinition}
     * and stores the result of the {@link Task} execution within the context for this {@link JobDefinition}.
     * The stored value is transient wiring for later steps: it is not persisted with the run's records,
     * and on resume the value is regenerated by executing the task again, so the task must be safe to re-run
     * @param task to add
     * @return this for fluent use
     */
    JobDefinition taskStoreResult(Task<?> task);

    /**
     * Adds a {@link Task} to the list of {@link Task}'s that will be executed by this {@link JobDefinition}
     * and stores the result of the {@link Task} execution within the context for this {@link JobDefinition}.
     * The stored value is transient wiring for later steps: it is not persisted with the run's records,
     * and on resume the value is regenerated by executing the task again, so the task must be safe to re-run
     * @param task to add
     * @param variableName the name to use when storing the {@link Task} result in the context for this {@link JobDefinition}
     * @return this for fluent use
     */
    JobDefinition taskStoreResult(Task<?> task, String variableName);

    /**
     * Adds a {@link Task} that creates external state, paired with the {@link Task} that reloads that
     * state from its source of truth. On the first run {@code createTask} executes; when a resumed run
     * finds this step already completed, {@code reloadTask} executes instead, so the creation is never
     * repeated. The stored value is not persisted with the run's records
     * @param createTask executed to create the state and store the result
     * @param reloadTask executed on resume to reload the state and store the result
     * @return this for fluent use
     */
    JobDefinition taskStoreResult(Task<?> createTask, Task<?> reloadTask);

    /**
     * Adds a {@link Task} that creates external state, paired with the {@link Task} that reloads that
     * state from its source of truth. On the first run {@code createTask} executes; when a resumed run
     * finds this step already completed, {@code reloadTask} executes instead, so the creation is never
     * repeated. The stored value is not persisted with the run's records
     * @param createTask executed to create the state and store the result
     * @param reloadTask executed on resume to reload the state and store the result
     * @param variableName the name to use when storing the result in the context for this {@link JobDefinition}
     * @return this for fluent use
     */
    JobDefinition taskStoreResult(Task<?> createTask, Task<?> reloadTask, String variableName);

    /**
     * Adds a {@link Task} to the list of {@link Task}'s that will be executed by this {@link JobDefinition}
     * and stores the result as durable state: the value is serialized into the run's records, and on
     * resume it is replayed from the record instead of executing the task again.
     * The stored value must serialize to JSON and back; a value that cannot fails the run at this step.
     * Bare collections and maps cannot be stored as state because their element types are erased -
     * wrap them in a domain class whose field declares the element type
     * @param task to add
     * @return this for fluent use
     */
    JobDefinition taskStoreState(Task<?> task);

    /**
     * Adds a {@link Task} to the list of {@link Task}'s that will be executed by this {@link JobDefinition}
     * and stores the result as durable state: the value is serialized into the run's records, and on
     * resume it is replayed from the record instead of executing the task again.
     * The stored value must serialize to JSON and back; a value that cannot fails the run at this step.
     * Bare collections and maps cannot be stored as state because their element types are erased -
     * wrap them in a domain class whose field declares the element type
     * @param task to add
     * @param variableName the name to use when storing the {@link Task} result in the context for this {@link JobDefinition}
     * @return this for fluent use
     */
    JobDefinition taskStoreState(Task<?> task, String variableName);

    /**
     * Adds a inner {@link JobDefinition} to this {@link JobDefinition}
     * @param jobDefinition to add into this {@link JobDefinition}
     * @return this for fluent use
     */
    JobDefinition jobDefinition(JobDefinition jobDefinition);

    /**
     * @return the {@link Step}'s defined for this {@link JobDefinition}
     */
    List<Step> getSteps();

    /**
     * Create a new {@link JobDefinition} with a {@link JobScope#CHILD} and {@link JobDefinition#isParallel()} is false
     * @return the new {@link JobDefinition}
     */
    static JobDefinition create(){
        return new DefaultJobDefinition(null, JobScope.CHILD, false);
    }


    static JobDefinition create(String description){
        return new DefaultJobDefinition(description, JobScope.CHILD, false);
    }

    static JobDefinition create(String description, JobScope jobScope){
        return new DefaultJobDefinition(description, jobScope, false);
    }

    static JobDefinition create(String description, JobScope jobScope, boolean parallel){
        return new DefaultJobDefinition(description, jobScope, parallel);
    }

    static JobDefinition create(String description, boolean parallel){
        return new DefaultJobDefinition(description, JobScope.CHILD, parallel);
    }


}
