// Models
export * from '@/api/model/idl/decorators/AutoGeneratedIdDecorator'
export * from '@/api/model/idl/decorators/DiscriminatorDecorator'
export * from '@/api/model/idl/decorators/EntityDecorator'
export * from '@/api/model/idl/decorators/EsIndexConfigurationDecorator'
export * from '@/api/model/idl/decorators/FlattenedDecorator'
export * from '@/api/model/idl/decorators/IdDecorator'
export * from '@/api/model/idl/decorators/NestedDecorator'
export * from '@/api/model/idl/decorators/NotIndexedDecorator'
export * from '@/api/model/idl/decorators/QueryDecorator'
export * from '@/api/model/idl/decorators/TenantIdDecorator'
export * from '@/api/model/idl/decorators/TextDecorator'
export * from '@/api/model/idl/decorators/TimeReferenceDecorator'
export * from '@/api/model/idl/decorators/VersionDecorator'

export * from '@/api/model/idl/PageC3Type'
export * from '@/api/model/idl/PageableC3Type'
export * from '@/api/model/idl/QueryOptionsC3Type'
export * from '@/api/model/idl/TenantSelectionC3Type'

export * from '@/api/model/Application'
export * from '@/api/model/Project'
export * from '@/api/model/ProjectType'
export * from '@/api/model/EntityDefinition'
export * from '@/api/model/NamedQueriesDefinition'
export * from '@/api/model/MigrationDefinition'
export * from '@/api/model/MigrationRequest'
export * from '@/api/model/MigrationResult'
export * from '@/api/model/insights/DataInsightsComponent'
export * from '@/api/model/insights/InsightProgress'
export * from '@/api/model/insights/InsightRequest'

export * from '@/api/model/Workload'
export * from '@/api/model/WorkloadStatus'
export * from '@/api/model/VmProviderType'
export * from '@/api/model/VmNode'
export * from '@/api/model/VmNodeRegistration'
export * from '@/api/model/VmNodeStatus'

// Services
export * from '@/api/services/IApplicationService'
export * from '@/api/services/ILogManager'
export * from '@/api/services/IProjectService'
export * from '@/api/services/LogManager'
export * from '@/api/services/IEntityDefinitionService'
export * from '@/api/services/INamedQueriesDefinitionService'
export * from '@/api/services/IMigrationService'
export * from '@/api/services/IDataInsightsService'
export * from '@/api/services/IVmNodeService'
export * from '@/api/services/IWorkloadService'

// Plugin
export * from '@/api/OsApiPlugin'

import type { IOsApiExtension } from '@/api/OsApiPlugin'

declare module '@kinotic-ai/core' {
    interface KinoticSingleton extends IOsApiExtension {}
}
