package org.kinotic.management.api.services.deployment;

import io.vertx.core.Future;
import org.kinotic.core.api.annotations.Publish;
import org.kinotic.management.api.model.deployment.ProjectSbom;

/**
 * The SBOMs of the caller's organization's projects, generated by the last step of every
 * deployment whose dependencies changed and kept in the organization's storage.
 */
@Publish
public interface ProjectSbomService {

    /**
     * Finds the SBOM of one of the caller's organization's projects.
     *
     * @param projectId a project belonging to the caller's organization
     * @return a future emitting the SBOM, or {@code null} when the project's deployments have not
     *         generated one
     */
    Future<ProjectSbom> findSbom(String projectId);

    /**
     * Finds a URL the CycloneDX JSON document of a project's SBOM can be read from for the next
     * fifteen minutes, by anyone holding it.
     *
     * @param projectId a project belonging to the caller's organization
     * @return a future emitting the URL, or {@code null} when the project has no SBOM
     */
    Future<String> findDocumentUrl(String projectId);

}
