import { IEntitiesService } from '@mindignited/structures-api'
import { BaseVehicleEntityService } from './generated/BaseVehicleEntityService.js'

/**
 * Service for interacting with Vehicle entities
 * This class was generated by the structures cli
 */
export class VehicleEntityService extends BaseVehicleEntityService {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
