import { IEntitiesService } from '@kinotic-ai/persistence'
import { BasePersonRepository } from './generated/BasePersonRepository.js'

/**
 * Service for interacting with Person entities
 * This class was generated by the structures cli
 */
export class PersonRepository extends BasePersonRepository {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
