package org.kinotic.test.probe;

import io.vertx.core.Future;
import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;

import java.util.concurrent.TimeUnit;
import org.kinotic.idl.api.schema.ArrayC3Type;
import org.kinotic.idl.api.schema.ObjectC3Type;
import org.kinotic.idl.api.schema.StringC3Type;
import org.kinotic.persistence.api.model.EntityDefinition;
import org.kinotic.persistence.api.model.idl.decorators.AutoGeneratedIdDecorator;
import org.kinotic.persistence.api.model.idl.decorators.EntityDecorator;
import org.kinotic.persistence.api.model.idl.decorators.MultiTenancyType;
import org.kinotic.persistence.api.model.idl.decorators.NestedDecorator;
import org.kinotic.persistence.api.services.EntityDefinitionService;
import org.kinotic.persistence.internal.api.services.EntityServiceCache;
import org.kinotic.test.support.kinotic.KinoticTestBase;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.TestPropertySource;

import java.util.List;

/**
 * THROWAWAY. Measures the marginal heap of one cached EntityService, for two schema shapes.
 */
@Slf4j
@TestPropertySource(properties = {"kinotic.persistence.numberOfShards=1",
                                  "kinotic.persistence.numberOfReplicas=0"})
public class EntityServiceHeapProbe extends KinoticTestBase {

    private static final int N = 100;

    @Autowired private EntityDefinitionService entityDefinitionService;
    @Autowired private EntityServiceCache entityServiceCache;

    /** Person shape: 9 leaf fields / 11 type nodes, matching load-generator Person. */
    private ObjectC3Type narrowSchema(String name){
        return new ObjectC3Type()
                .setName(name).setNamespace("probe")
                .addProperty("id", new StringC3Type(), List.of(new AutoGeneratedIdDecorator()))
                .addProperty("firstName", new StringC3Type())
                .addProperty("lastName", new StringC3Type())
                .addProperty("birthDate", new StringC3Type())
                .addProperty("age", new StringC3Type())
                .addProperty("address", new ObjectC3Type().setName(name + "Address")
                        .addProperty("street", new StringC3Type())
                        .addProperty("city", new StringC3Type())
                        .addProperty("state", new StringC3Type())
                        .addProperty("zip", new StringC3Type()))
                .addDecorator(new EntityDecorator().setMultiTenancyType(MultiTenancyType.NONE));
    }

    /** Provider shape: ~257 leaf fields / ~296 type nodes, matching load-generator Provider+Qualifications. */
    private ObjectC3Type wideSchema(String name){
        ObjectC3Type ret = new ObjectC3Type()
                .setName(name).setNamespace("probe")
                .addProperty("id", new StringC3Type(), List.of(new AutoGeneratedIdDecorator()));
        // 12 nested groups of 4 sub-objects of 5 fields = 240 leaves + 12 top-level scalars
        for (int g = 0; g < 12; g++) {
            ObjectC3Type group = new ObjectC3Type().setName(name + "Group" + g);
            for (int s = 0; s < 4; s++) {
                ObjectC3Type sub = new ObjectC3Type().setName(name + "Sub" + g + "_" + s);
                for (int f = 0; f < 5; f++) {
                    sub.addProperty("field" + f, new StringC3Type());
                }
                group.addProperty("sub" + s, new ArrayC3Type().setContains(sub), List.of(new NestedDecorator()));
            }
            ret.addProperty("group" + g, group);
            ret.addProperty("scalar" + g, new StringC3Type());
        }
        return ret.addDecorator(new EntityDecorator().setMultiTenancyType(MultiTenancyType.NONE));
    }

    private long usedHeapAfterGc() throws Exception {
        long prev = -1, cur = 0;
        for (int i = 0; i < 12 && prev != cur; i++) {   // settle: repeat until two reads agree
            prev = cur;
            System.gc();
            Thread.sleep(300);
            cur = (Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory()) >> 10;
        }
        return cur;
    }

    private void measure(String label, boolean wide) throws Exception {
        long t0 = System.currentTimeMillis();
        String prefix = (wide ? "wide" : "narrow") + System.nanoTime() % 100000;
        for (int i = 0; i < N; i++) {
            String n = prefix + "e" + i;
            EntityDefinition def = new EntityDefinition()
                    .setName(n).setApplicationId(TEST_APP_ID).setProjectId(TEST_APP_ID)
                    .setOrganizationId(TEST_ORG_ID)
                    .setSchema(wide ? wideSchema(n) : narrowSchema(n));
            EntityDefinition created = runAsOrganization(() -> entityDefinitionService.create(def)).await();
            runAsOrganization(() -> entityDefinitionService.publish(created.getId())).await();
            if (i % 25 == 0) log.error("PROBE[{}] published {}/{}", label, i, N);
        }
        long before = usedHeapAfterGc();

        for (int i = 0; i < N; i++) {
            String id = prefix + "e" + i;
            runAsOrganization(() -> entityServiceCache.get(TEST_ORG_ID,
                    org.kinotic.persistence.internal.utils.PersistenceUtil
                            .createEntityDefinitionId(TEST_ORG_ID, TEST_APP_ID, id))).await();
        }
        long after = usedHeapAfterGc();

        long deltaKb = after - before;
        log.error("PROBE[{}] N={} beforeKB={} afterKB={} deltaKB={} bytesPerEntityService={} elapsedSec={}",
                  label, N, before, after, deltaKb, (deltaKb * 1024) / N,
                  (System.currentTimeMillis() - t0) / 1000);
    }

    @Test
    @Timeout(value = 40, unit = TimeUnit.MINUTES)
    public void measureBothShapes() throws Exception {
        measure("warmup", false);
        measure("narrow", false);
        measure("wide", true);
    }
}
