import { createHash } from 'node:crypto'
import { existsSync, readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { run } from './log.ts'

/**
 * The SBOM of a project checkout: a CycloneDX 1.6 JSON document of every package its `bun.lock`
 * resolves, generated by cdxgen, the CycloneDX project's generator, which reads the lockfile and
 * looks up each package's license in the npm registry. cdxgen is a dependency of this runner, so
 * a project declares nothing to have an SBOM.
 */

/** The lockfile the SBOM lists the packages of, at the root of the checkout. */
const LOCKFILE = 'bun.lock'

const CDXGEN_PACKAGE_JSON = Bun.resolveSync('@cyclonedx/cdxgen/package.json', import.meta.dir)
const cdxgen = JSON.parse(readFileSync(CDXGEN_PACKAGE_JSON, 'utf-8')) as { version: string, bin: { cdxgen: string } }

/** The parts of a CycloneDX document the runner reads. */
export interface CycloneDxDocument {
    bomFormat: string
    specVersion: string
    components?: unknown[]
}

/**
 * A SHA-256 of the checkout's `bun.lock` and of the cdxgen version, everything the SBOM is
 * generated from, so two checkouts with the same hash have the same SBOM; `null` when the checkout
 * has no `bun.lock`.
 */
export function dependencyHashOf(workspaceDir: string): string | null {
    const lockfile = join(workspaceDir, LOCKFILE)
    let ret: string | null = null
    if (existsSync(lockfile)) {
        ret = createHash('sha256').update(`cdxgen ${cdxgen.version}\n`).update(readFileSync(lockfile)).digest('hex')
    }
    return ret
}

/**
 * Generates the checkout's SBOM into `outputFile` and returns it. cdxgen only reads the checkout,
 * which may be mounted read-only.
 */
export async function generateSbom(workspaceDir: string, outputFile: string): Promise<CycloneDxDocument> {
    // --no-install-deps: cdxgen otherwise installs what a checkout lacks, and this one is installed
    await run('bun', [join(dirname(CDXGEN_PACKAGE_JSON), cdxgen.bin.cdxgen),
                      '--type', 'js', '--no-install-deps', '--spec-version', '1.6', '--output', outputFile, workspaceDir],
              dirname(outputFile), { FETCH_LICENSE: 'true' })
    return JSON.parse(readFileSync(outputFile, 'utf-8')) as CycloneDxDocument
}
