package org.kinotic.management.internal.api.services;

import io.vertx.core.CompositeFuture;
import io.vertx.core.Future;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.Validate;
import org.kinotic.core.api.security.SecurityContext;
import org.kinotic.domain.api.config.DomainPersistenceProperties;
import org.kinotic.domain.api.model.persistence.DecoratedProperty;
import org.kinotic.domain.api.model.persistence.EntityDefinition;
import org.kinotic.domain.api.model.persistence.idl.decorators.AutoGeneratedIdDecorator;
import org.kinotic.domain.api.model.persistence.idl.decorators.IdDecorator;
import org.kinotic.domain.api.model.persistence.idl.decorators.MultiTenancyType;
import org.kinotic.domain.api.model.security.participant.OrganizationParticipant;
import org.kinotic.domain.api.repositories.EntityDefinitionRepository;
import org.kinotic.domain.api.utils.DomainUtil;
import org.kinotic.domain.internal.api.services.CrudServiceTemplate;
import org.kinotic.management.api.model.MigrationDefinition;
import org.kinotic.management.api.model.MigrationRequest;
import org.kinotic.management.api.model.MigrationResult;
import org.kinotic.management.api.model.Project;
import org.kinotic.management.api.repositories.ProjectRepository;
import org.kinotic.management.api.services.MigrationService;
import org.kinotic.sql.domain.Migration;
import org.kinotic.sql.domain.MigrationContent;
import org.kinotic.sql.domain.Statement;
import org.kinotic.sql.domain.statements.DeleteStatement;
import org.kinotic.sql.domain.statements.InsertStatement;
import org.kinotic.sql.domain.statements.ReindexStatement;
import org.kinotic.sql.domain.statements.UpdateStatement;
import org.kinotic.sql.executor.MigrationExecutor;
import org.kinotic.sql.parsers.MigrationParser;
import org.springframework.stereotype.Component;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Function;

/**
 * Runs an organization's migrations against the entities of one of its applications. A migration names entities,
 * and every statement is addressed at the index of the entity it names before any of them runs.
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class DefaultMigrationService implements MigrationService {

    private final CrudServiceTemplate crudServiceTemplate;
    private final MigrationExecutor migrationExecutor;
    private final MigrationParser migrationParser;
    private final SecurityContext securityContext;
    private final ProjectRepository projectRepository;
    private final EntityDefinitionRepository entityDefinitionRepository;
    private final DomainPersistenceProperties domainPersistenceProperties;

    @Override
    public Future<MigrationResult> executeMigrations(MigrationRequest migrationRequest) {
        String projectId = migrationRequest.projectId();
        OrganizationParticipant participant = securityContext.requireParticipant(OrganizationParticipant.class);
        log.debug("Executing {} migrations for project {}", migrationRequest.migrations().size(), projectId);
        return requireOwnedProject(projectId, participant)
                .compose(project -> resolve(migrationRequest.migrations(), project))
                .compose(migrations -> crudServiceTemplate.toFuture(migrationExecutor.executeProjectMigrations(migrations, projectId))
                                                          .map(v -> MigrationResult.success(projectId, migrations.size())))
                .otherwise(throwable -> {
                    log.debug("Failed to execute migrations for project {}: {}", projectId, throwable.getMessage(), throwable);
                    return MigrationResult.failure(projectId, throwable.getMessage());
                });
    }

    @Override
    public Future<Integer> getLastAppliedMigrationVersion(String projectId) {
        OrganizationParticipant participant = securityContext.requireParticipant(OrganizationParticipant.class);
        return requireOwnedProject(projectId, participant)
                .compose(project -> crudServiceTemplate.toFuture(migrationExecutor.getLastAppliedMigrationVersion(projectId)));
    }

    @Override
    public Future<Boolean> isMigrationApplied(String projectId, String version) {
        Validate.notNull(version, "Migration version cannot be null");
        OrganizationParticipant participant = securityContext.requireParticipant(OrganizationParticipant.class);
        return requireOwnedProject(projectId, participant)
                .compose(project -> crudServiceTemplate.toFuture(migrationExecutor.isMigrationAppliedAsync(version, projectId)));
    }

    /**
     * Loads a project of the participant's organization.
     */
    private Future<Project> requireOwnedProject(String projectId, OrganizationParticipant participant) {
        Validate.notNull(projectId, "Project ID cannot be null");
        // the system migrations are recorded under this project id, so a project of that id would read and
        // write their history
        Validate.isTrue(!MigrationExecutor.SYSTEM_PROJECT.equals(projectId), "Project ID %s is not allowed", projectId);
        String organizationId = participant.getOrganizationId();
        // a missing project and another organization's fail the same way: no existence oracle
        return projectRepository.findById(projectId, organizationId)
                                .map(project -> DomainUtil.requireOwned(project, organizationId, "Project " + projectId + " not found"));
    }

    /**
     * Parses every migration and addresses each of its statements at the index of the entity it names, so a
     * syntax error, a statement that is not a data statement, or a name that is not one of the application's
     * published entities fails the request before anything runs.
     */
    private Future<List<Migration>> resolve(List<MigrationDefinition> definitions, Project project) {
        // one lookup per distinct name, shared by every statement that names the entity
        Map<String, Future<EntityDefinition>> lookups = new HashMap<>();
        Function<String, Future<EntityDefinition>> entity = name -> lookups.computeIfAbsent(name, n -> requireEntity(n, project));
        List<Future<Migration>> migrations = definitions.stream().map(definition -> resolve(definition, entity)).toList();
        return Future.all(migrations).map(CompositeFuture::list);
    }

    private Future<Migration> resolve(MigrationDefinition definition, Function<String, Future<EntityDefinition>> entity) {
        List<Future<Statement>> statements = migrationParser.parse(definition.content(), definition.name()).statements().stream()
                                                            .map(statement -> address(statement, entity, definition))
                                                            .toList();
        return Future.all(statements)
                     .map(composite -> new ResolvedMigration(definition.version(), definition.name(), new MigrationContent(composite.list())));
    }

    private Future<EntityDefinition> requireEntity(String name, Project project) {
        String organizationId = project.getOrganizationId();
        String id = DomainUtil.createEntityDefinitionId(organizationId, project.getApplicationId(), name);
        return entityDefinitionRepository.findById(id, organizationId)
                                         .map(definition -> {
                                             Validate.isTrue(definition != null && definition.isPublished(),
                                                             "Application %s has no published entity named %s",
                                                             project.getApplicationId(), name);
                                             return definition;
                                         });
    }

    /**
     * Addresses a statement at the index of the entity it names. An INSERT also gets the document id and routing
     * the entity service gives a row it saves.
     */
    private Future<Statement> address(Statement statement,
                                      Function<String, Future<EntityDefinition>> entity,
                                      MigrationDefinition definition) {
        return switch (statement) {
            case InsertStatement insert -> entity.apply(insert.tableName())
                                                 .map(target -> identify(insert, target));
            case UpdateStatement update -> entity.apply(update.tableName())
                                                 .map(target -> new UpdateStatement(target.getItemIndex(), update.assignments(),
                                                                                    update.whereClause(), update.refresh()));
            case DeleteStatement delete -> entity.apply(delete.tableName())
                                                 .map(target -> new DeleteStatement(target.getItemIndex(), delete.whereClause(), delete.refresh()));
            case ReindexStatement reindex -> Future.all(entity.apply(reindex.source()), entity.apply(reindex.dest()))
                                                   .map(targets -> new ReindexStatement(targets.<EntityDefinition>resultAt(0).getItemIndex(),
                                                                                        targets.<EntityDefinition>resultAt(1).getItemIndex(),
                                                                                        reindex.conflicts(), reindex.maxDocs(), reindex.slices(),
                                                                                        reindex.size(), reindex.sourceFields(), reindex.query(),
                                                                                        reindex.script(), reindex.waitForReindex(),
                                                                                        reindex.skipIfNoSource()));
            default -> Future.failedFuture(new IllegalArgumentException(
                    "Migration " + definition.name() + ": a project migration acts on the application's entities with INSERT, UPDATE, DELETE and REINDEX, so "
                            + statement.getClass().getSimpleName().replace("Statement", "") + " is not allowed"));
        };
    }

    /**
     * Addresses an INSERT at the entity's index with the document id and routing the entity service gives a row it
     * saves, so the row is reachable through the entity's repository afterwards: the document id from the row's id
     * field, and on a multi-tenant entity both from its tenant field as well.
     */
    private InsertStatement identify(InsertStatement insert, EntityDefinition definition) {
        Validate.isTrue(insert.routing() == null && insert.documentId() == null,
                        "INSERT INTO %s: ROUTING and DOCUMENT_ID are derived from the row's fields", definition.getName());
        Validate.isTrue(insert.columns().size() == insert.values().size(),
                        "INSERT INTO %s lists %d columns and %d values", definition.getName(), insert.columns().size(), insert.values().size());
        String id = requireColumnValue(insert, definition, idFieldName(definition));
        String tenantId;
        if (definition.getMultiTenancyType() == MultiTenancyType.SHARED) {
            // an entity that declares no tenant id field of its own holds the tenant in the platform's field
            String tenantField = definition.getTenantIdFieldName() != null
                    ? definition.getTenantIdFieldName()
                    : domainPersistenceProperties.getTenantIdFieldName();
            tenantId = requireColumnValue(insert, definition, tenantField);
        } else {
            tenantId = null;
        }
        return new InsertStatement(definition.getItemIndex(), insert.columns(), insert.values(), insert.refresh(), tenantId,
                                   DomainUtil.createEntityDocumentId(definition.getMultiTenancyType(), tenantId, id));
    }

    private static String idFieldName(EntityDefinition definition) {
        return definition.getDecoratedProperties().stream()
                         // only a top-level field identifies the row; a nested object's id is just a value of it
                         .filter(property -> !property.getJsonPath().contains("."))
                         .filter(property -> property.findDecorator(IdDecorator.class) != null
                                 || property.findDecorator(AutoGeneratedIdDecorator.class) != null)
                         .map(DecoratedProperty::getJsonPath)
                         .findFirst()
                         .orElseThrow(() -> new IllegalStateException("Entity " + definition.getName() + " has no id field"));
    }

    /**
     * The value an INSERT gives a column, which the row has to carry as a non-blank string.
     */
    private static String requireColumnValue(InsertStatement insert, EntityDefinition definition, String column) {
        int position = insert.columns().indexOf(column);
        Validate.isTrue(position >= 0, "INSERT INTO %s must list the %s column", definition.getName(), column);
        Object value = insert.values().get(position);
        Validate.isTrue(value instanceof String text && !text.isBlank(),
                        "INSERT INTO %s: %s must be a non-blank string", definition.getName(), column);
        return (String) value;
    }
}
