<script setup lang="ts">
/** One coloured run of text inside a code pane line. */
interface Token {
  /**
   * comment · keyword · plain · type · annotation · generated · dim · bright · success
   */
  kind: 'c' | 'k' | 'p' | 't' | 'a' | 'g' | 'd' | 'b' | 's'
  text: string
}

interface Capability {
  id: string
  title: string
  summary: string
  icon: 'Frontends' | 'Microservices' | 'McpTools' | 'Persistence'
  file: string
  code: Token[][]
}

const t = (kind: Token['kind'], text: string): Token => ({ kind, text })

const capabilities: Capability[] = [
  {
    id: 'frontends',
    title: 'Frontends',
    summary: 'Complete UIs deployed as static sites, wired to your services with auth included.',
    icon: 'Frontends',
    file: 'web/src/todos.ts',
    code: [
      [t('c', '// your UI — React, Vue, or plain TS')],
      [t('k', 'await'), t('p', ' Kinotic.connect()')],
      [t('c', '// call any repository or microservice')],
      [t('k', 'const'), t('p', ' todos = '), t('k', 'new'), t('p', ' TodoRepository()')],
      [t('k', 'const'), t('p', ' page = '), t('k', 'await'), t('p', ' todos.findAll({')],
      [t('p', '  page: '), t('t', '0'), t('p', ', size: '), t('t', '25'), t('p', ' })')],
      [t('k', 'await'), t('k', ' new'), t('p', ' TodoService(Kinotic)')],
      [t('p', '  .complete(page.content['), t('t', '0'), t('p', '].id)')],
      [],
      [t('c', '// the platform provides:')],
      [t('g', '→ static hosting on a CDN')],
      [t('g', '→ session wiring to your services')],
      [t('g', '→ a preview environment per branch')],
      [t('d', '$ '), t('b', 'git push')],
      [t('s', '✓ '), t('b', 'todo-console '), t('s', 'deployed')],
    ],
  },
  {
    id: 'microservices',
    title: 'Microservices',
    summary: 'Long-running services with a generated proxy for every published call.',
    icon: 'Microservices',
    file: 'services/src/TodoService.ts',
    code: [
      [t('c', '// callee — publish the service')],
      [t('a', '@Publish'), t('p', '('), t('t', "'com.example'"), t('p', ')')],
      [t('k', 'class'), t('p', ' TodoService {')],
      [t('p', '  complete(id: '), t('t', 'string'), t('p', ') { ... }')],
      [t('p', '}')],
      [t('c', '// caller — another service or your UI')],
      [t('k', 'const'), t('p', ' todos = '), t('k', 'new'), t('p', ' TodoService(Kinotic)')],
      [t('k', 'const'), t('p', ' todo = '), t('k', 'await'), t('p', ' todos.complete(id)')],
      [],
      [t('c', '// the platform provides:')],
      [t('g', '→ a typed proxy for every call')],
      [t('g', '→ tracing across service boundaries')],
      [t('d', '$ '), t('b', 'git push')],
      [t('s', '✓ '), t('b', 'todo-service '), t('s', 'live')],
    ],
  },
  {
    id: 'mcp-tools',
    title: 'MCP Tools',
    summary: 'Publish a method as an MCP tool — build against live data with Claude, ChatGPT or Cursor.',
    icon: 'McpTools',
    file: 'services/src/TodoService.ts',
    code: [
      [t('c', '// the same service, now an MCP tool')],
      [t('a', '@Publish'), t('p', '('), t('t', "'com.example'"), t('p', ')')],
      [t('k', 'class'), t('p', ' TodoService {')],
      [t('p', '  '), t('a', '@McpTool'), t('p', '({')],
      [t('p', '    title: '), t('t', "'Find Todo'"), t('p', ',')],
      [t('p', '    description: '), t('t', "'Find a todo by id'"), t('p', ',')],
      [t('p', '    readOnlyHint: '), t('t', 'true')],
      [t('p', '  })')],
      [t('p', '  findById(id: '), t('t', 'string'), t('p', ') { ... }')],
      [t('p', '}')],
      [],
      [t('c', '// the platform provides:')],
      [t('g', '→ tools served at POST /mcp')],
      [t('g', '→ callers see only their own tools')],
      [t('g', '→ works with Claude, ChatGPT, Cursor')],
    ],
  },
  {
    id: 'persistence',
    title: 'Persistence',
    summary: 'Domain models with a generated repository, search, pagination and named queries.',
    icon: 'Persistence',
    file: 'data/src/Todo.ts',
    code: [
      [t('c', '// define the domain model')],
      [t('a', '@Entity'), t('p', '()')],
      [t('k', 'export class'), t('p', ' Todo {')],
      [t('p', '  '), t('a', '@AutoGeneratedId')],
      [t('p', '  id: '), t('t', 'string | null'), t('p', ' = '), t('t', 'null')],
      [t('p', '  '), t('a', '@NotNull')],
      [t('p', '  title: '), t('t', 'string'), t('p', ' = '), t('t', "''")],
      [t('p', '}')],
      [],
      [t('d', '$ '), t('b', 'kinotic generate')],
      [t('s', '✓ '), t('b', 'TodoRepository '), t('s', 'generated')],
      [t('c', '// Crud operations for free')],
      [t('k', 'const'), t('p', ' todos = '), t('k', 'new'), t('p', ' TodoRepository()')],
      [t('k', 'const'), t('p', ' saved = '), t('k', 'await'), t('p', ' todos.save(todo)')],
      [t('k', 'const'), t('p', ' found = '), t('k', 'await'), t('p', ' todos.findById(id)')],
    ],
  },
]

const activeIndex = ref(0)
const active = computed(() => capabilities[activeIndex.value]!)
const tabs = useTemplateRef<HTMLButtonElement[]>('tabs')

/** Roving focus across the tab list, per the WAI-ARIA tabs pattern. */
function onTabKeydown(event: KeyboardEvent) {
  const last = capabilities.length - 1
  let next: number
  if (event.key === 'ArrowDown' || event.key === 'ArrowRight') next = activeIndex.value === last ? 0 : activeIndex.value + 1
  else if (event.key === 'ArrowUp' || event.key === 'ArrowLeft') next = activeIndex.value === 0 ? last : activeIndex.value - 1
  else if (event.key === 'Home') next = 0
  else if (event.key === 'End') next = last
  else return

  event.preventDefault()
  activeIndex.value = next
  tabs.value?.[next]?.focus()
}
</script>

<template>
  <section class="k-section api">
    <div class="api__glow" />
    <div class="k-wrap api__inner">
      <div class="k-eyebrow api__eyebrow" data-reveal>
        <span>STUPID SIMPLE API</span>
      </div>
      <h2 class="k-heading api__title" data-reveal>Unparalleled time to delivery</h2>

      <div class="api__panel" data-reveal>
        <div class="api__list" role="tablist" aria-label="Kinotic capabilities" @keydown="onTabKeydown">
          <button
            v-for="(capability, index) in capabilities"
            :key="capability.id"
            ref="tabs"
            type="button"
            role="tab"
            class="api__tab"
            :class="{ 'api__tab--active': index === activeIndex }"
            :id="`api-tab-${capability.id}`"
            :aria-selected="index === activeIndex"
            :aria-controls="`api-panel-${capability.id}`"
            :tabindex="index === activeIndex ? 0 : -1"
            @click="activeIndex = index"
          >
            <span class="api__tabicon">
              <KinoticIcon :name="capability.icon" :size="20" />
            </span>
            <span>
              <span class="api__tabtitle">{{ capability.title }}</span>
              <span class="api__tabsummary">{{ capability.summary }}</span>
            </span>
          </button>
        </div>

        <div
          class="api__code"
          role="tabpanel"
          :id="`api-panel-${active.id}`"
          :aria-labelledby="`api-tab-${active.id}`"
          tabindex="0"
        >
          <div class="api__codebar">
            <span class="api__dots">
              <span /><span /><span />
            </span>
            <span class="api__file">{{ active.file }}</span>
          </div>
          <pre class="api__pre"><div v-for="(line, index) in active.code" :key="index"><span
            v-for="(token, tokenIndex) in line"
            :key="tokenIndex"
            :class="`tok tok--${token.kind}`"
          >{{ token.text }}</span></div></pre>
        </div>
      </div>

      <div class="api__cta" data-reveal>
        <a href="#cta" class="k-btn k-btn--red">Get Started ↗</a>
      </div>
    </div>
  </section>
</template>

<style scoped>
.api {
  position: relative;
  overflow: hidden;
}

.api__glow {
  position: absolute;
  top: 0;
  right: -120px;
  width: 520px;
  height: 380px;
  background: radial-gradient(ellipse, rgba(236, 31, 82, 0.12), transparent 70%);
  filter: blur(10px);
  pointer-events: none;
}

.api__inner {
  position: relative;
}

.api__eyebrow {
  justify-content: center;
  margin-bottom: 18px;
}

.api__title {
  font-size: clamp(29px, 3.6vw, 46px);
  text-align: center;
  margin-bottom: 64px;
}

.api__panel {
  display: grid;
  grid-template-columns: 5fr 7fr;
  border: 1px solid var(--color-k-border);
  background: var(--color-k-bg);
}

.api__list {
  display: flex;
  flex-direction: column;
  border-right: 1px solid var(--color-k-border);
}

.api__tab {
  flex: 1;
  display: flex;
  gap: 18px;
  padding: 26px 30px;
  text-align: left;
  background: transparent;
  border: none;
  border-bottom: 1px solid var(--color-k-border);
  cursor: pointer;
  transition: background 0.2s ease;
}

.api__tab:last-child {
  border-bottom: none;
}

.api__tab:hover {
  background: rgba(255, 255, 255, 0.025);
}

.api__tab--active {
  background: rgba(40, 254, 180, 0.04);
}

.api__tabicon {
  flex: none;
  width: 44px;
  height: 44px;
  border-radius: 8px;
  border: 1px solid rgba(255, 255, 255, 0.12);
  color: var(--color-k-dim);
  background: var(--color-k-bg-panel);
  display: inline-flex;
  align-items: center;
  justify-content: center;
  transition: border-color 0.2s ease, color 0.2s ease;
}

.api__tab--active .api__tabicon {
  border-color: rgba(40, 254, 180, 0.55);
  color: var(--color-k-mint);
}

.api__tabtitle {
  display: block;
  font-family: var(--font-k-mono);
  font-size: 16.5px;
  color: var(--color-k-text);
  margin-bottom: 7px;
}

.api__tabsummary {
  display: block;
  font-size: 13.5px;
  line-height: 1.6;
  color: var(--color-k-muted);
}

.api__code {
  background: #0A0A0C;
  padding: 26px 34px;
  position: relative;
  min-height: 420px;
}

.api__codebar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 26px;
}

.api__dots {
  display: inline-flex;
  gap: 7px;
}

.api__dots span {
  width: 9px;
  height: 9px;
  border-radius: 50%;
  background: #D6D6DB;
}

.api__dots span:nth-child(2) {
  background: var(--color-k-fainter);
}

.api__dots span:nth-child(3) {
  background: #3A3A40;
}

.api__file {
  font-family: var(--font-k-mono);
  font-size: 11.5px;
  color: var(--color-k-fainter);
}

/* A row carrying no tokens is a deliberate blank line between the code and the
   commentary under it; an empty div would otherwise collapse to no height. */
.api__pre > div:empty {
  height: 1lh;
}

.api__pre {
  margin: 0;
  font-family: var(--font-k-mono);
  font-size: 13px;
  line-height: 2.05;
  color: var(--color-k-body);
  white-space: pre-wrap;
}

.tok--c { color: var(--color-k-fainter); }
.tok--k { color: var(--color-k-mint); }
.tok--p { color: var(--color-k-body); }
.tok--t { color: #EC5C7F; }
.tok--a { color: var(--color-k-mint); }
.tok--g { color: var(--color-k-dim); }
.tok--d { color: var(--color-k-fainter); }
.tok--b { color: var(--color-k-text); }
.tok--s { color: var(--color-k-mint); }

.api__cta {
  display: flex;
  justify-content: center;
  margin-top: 56px;
}

@media (max-width: 930px) {
  .api__panel {
    grid-template-columns: 1fr;
  }

  .api__list {
    border-right: none;
    border-bottom: 1px solid var(--color-k-border);
  }
}

@media (max-width: 600px) {
  .api__tab {
    padding: 22px 18px;
  }

  .api__code {
    padding: 20px 16px;
    min-height: 0;
  }

  .api__pre {
    font-size: 12px;
    line-height: 1.95;
  }
}
</style>
