<script setup lang="ts">
/** One coloured run of text inside a code pane line. */
interface Token {
  /**
   * comment · keyword · plain · type · annotation · generated · dim · bright · success
   */
  kind: 'c' | 'k' | 'p' | 't' | 'a' | 'g' | 'd' | 'b' | 's'
  text: string
}

/** One code pane inside a step — a step shows 1 to 3 of them in turn. */
interface Slide {
  file: string
  code: Token[][]
}

/** One beat of the build walkthrough, shown as a rail entry and its slides. */
interface Step {
  id: string
  number: string
  title: string
  summary: string
  icon: 'Prompt' | 'Persistence' | 'Microservices' | 'Frontends' | 'McpTools'
  slides: Slide[]
}

const t = (kind: Token['kind'], text: string): Token => ({ kind, text })

const steps: Step[] = [
  {
    id: 'describe',
    number: '01',
    title: 'Describe it',
    summary: 'Tell your assistant what you need. It creates the application, the project and the repo.',
    icon: 'Prompt',
    slides: [
      {
        file: 'claude · kinotic plugin',
        code: [
          [t('d', '> '), t('b', '/kinotic:new-app')],
          [t('p', '"A todo app for our field techs"')],
          [],
          [t('c', '// Kinotic OS, over MCP')],
          [t('s', '✓ '), t('b', 'Application  '), t('s', 'todo-app')],
          [t('s', '✓ '), t('b', 'Project      '), t('s', 'field-ops')],
          [t('s', '✓ '), t('b', 'GitHub repo  '), t('s', 'provisioned')],
          [],
          [t('c', '// nothing to install globally: the')],
          [t('c', '// repo is a Bun workspace with the')],
          [t('c', '// CLI already vendored in')],
        ],
      },
      {
        file: '~/todo-app',
        code: [
          [t('d', '$ '), t('b', 'git clone'), t('p', ' … && '), t('b', 'bun install')],
          [],
          [t('p', 'todo-app/')],
          [t('p', '  .config/kinotic.config.ts')],
          [t('p', '  packages/')],
          [t('p', '    domain/model/'), t('c', '        // entities')],
          [t('p', '    domain/repositories/'), t('c', ' // generated')],
          [t('p', '    microservices/main/'), t('c', '  // services')],
          [t('p', '    web/'), t('c', '                 // the UI')],
          [],
          [t('c', '// the config is already wired to your')],
          [t('c', '// organization and application')],
        ],
      },
    ],
  },
  {
    id: 'model',
    number: '02',
    title: 'Model the domain',
    summary: 'A decorated class per entity. The CLI generates its repository, named queries included.',
    icon: 'Persistence',
    slides: [
      {
        file: 'domain/model/Todo.ts',
        code: [
          [t('d', '> '), t('b', '"a Todo has a title, a priority')],
          [t('b', '   and a done flag, per tenant"')],
          [],
          [t('c', '// Todo.ts — written for you')],
          [t('a', '@Entity'), t('p', '('), t('t', 'MultiTenancyType.SHARED'), t('p', ')')],
          [t('k', 'export class'), t('p', ' Todo {')],
          [t('p', '  '), t('a', '@AutoGeneratedId')],
          [t('p', '  id: '), t('t', 'string | null'), t('p', ' = '), t('t', 'null')],
          [t('p', '  '), t('a', '@TenantId')],
          [t('p', '  tenantId: '), t('t', 'string'), t('p', ' = '), t('t', "''")],
          [t('p', '  '), t('a', '@NotNull'), t('p', ' '), t('a', '@Text')],
          [t('p', '  title: '), t('t', 'string'), t('p', ' = '), t('t', "''")],
          [t('p', '  '), t('a', '@Precision'), t('p', '('), t('t', 'PrecisionType.SHORT'), t('p', ')')],
          [t('p', '  priority: '), t('t', 'number'), t('p', ' = '), t('t', '0')],
          [t('p', '  done: '), t('t', 'boolean'), t('p', ' = '), t('t', 'false')],
          [t('p', '}')],
        ],
      },
      {
        file: 'domain/repositories/TodoRepository.ts',
        code: [
          [t('d', '$ '), t('b', 'bun run generate')],
          [t('s', '✓ '), t('b', 'TodoRepository'), t('p', ' + base class')],
          [],
          [t('d', '> '), t('b', '"add a count of what is still open"')],
          [],
          [t('c', '// yours to extend, body generated')],
          [t('k', 'export class'), t('p', ' TodoRepository')],
          [t('p', '    '), t('k', 'extends'), t('p', ' BaseTodoRepository {')],
          [t('p', '  '), t('a', '@Query'), t('p', '(')],
          [t('p', '    '), t('t', "'SELECT COUNT(*) FROM Todo'")],
          [t('p', '    '), t('t', "+ ' WHERE done = :done'"), t('p', ')')],
          [t('p', '  countByDone(done: '), t('t', 'boolean'), t('p', ')')],
          [t('p', '    : '), t('t', 'Promise<number>'), t('p', ' { }')],
          [t('p', '}')],
        ],
      },
      {
        file: 'microservices/main/src/main.ts',
        code: [
          [t('d', '> '), t('b', '"seed a couple and find the open ones"')],
          [],
          [t('p', 'Kinotic.'), t('b', 'use'), t('p', '(PersistencePlugin)')],
          [t('k', 'await'), t('p', ' Kinotic.connect()')],
          [],
          [t('k', 'const'), t('p', ' todos = '), t('k', 'new'), t('p', ' TodoRepository()')],
          [t('k', 'await'), t('p', ' todos.save({')],
          [t('p', '  id: '), t('t', 'null'), t('p', ', title: '), t('t', "'Regrease the pump'"), t('p', ',')],
          [t('p', '  priority: '), t('t', '2'), t('p', ', done: '), t('t', 'false')],
          [t('p', '})')],
          [],
          [t('k', 'const'), t('p', ' page = '), t('k', 'await'), t('p', ' todos.search('), t('t', "'pump'"), t('p', ', {')],
          [t('p', '  page: '), t('t', '0'), t('p', ', size: '), t('t', '20'), t('p', ' })')],
          [t('k', 'const'), t('p', ' open = '), t('k', 'await'), t('p', ' todos')],
          [t('p', '  .countByDone('), t('t', 'false'), t('p', ')')],
        ],
      },
    ],
  },
  {
    id: 'publish',
    number: '03',
    title: 'Publish the behavior',
    summary: 'Any class becomes a remote service. Callers reach it through a typed proxy.',
    icon: 'Microservices',
    slides: [
      {
        file: 'microservices/main/src/TodoService.ts',
        code: [
          [t('d', '> '), t('b', '"add a service that completes one"')],
          [],
          [t('c', '// TodoService.ts — written for you')],
          [t('a', '@Publish'), t('p', '('), t('t', "'com.example'"), t('p', ')')],
          [t('k', 'export class'), t('p', ' TodoService {')],
          [t('p', '  '), t('k', 'constructor'), t('p', '(')],
          [t('p', '    '), t('k', 'private'), t('p', ' todos: TodoRepository) {}')],
          [],
          [t('p', '  '), t('k', 'async'), t('p', ' complete(id: '), t('t', 'string'), t('p', ') {')],
          [t('p', '    '), t('k', 'const'), t('p', ' todo = '), t('k', 'await'), t('p', ' this.todos')],
          [t('p', '      .findById(id)')],
          [t('p', '    todo.done = '), t('t', 'true')],
          [t('p', '    '), t('k', 'return'), t('p', ' this.todos.update(todo)')],
          [t('p', '  }')],
          [t('p', '}')],
        ],
      },
      {
        file: 'web/src/TodoServiceProxy.ts',
        code: [
          [t('d', '> '), t('b', '"let the console call it"')],
          [],
          [t('c', '// a typed proxy, also written for you')],
          [t('k', 'export class'), t('p', ' TodoServiceProxy')],
          [t('p', '    '), t('k', 'implements'), t('p', ' ITodoService {')],
          [t('p', '  '), t('k', 'private readonly'), t('p', ' proxy: IServiceProxy')],
          [t('p', '  '), t('k', 'constructor'), t('p', '(kinotic: IKinotic) {')],
          [t('p', '    this.proxy = kinotic.serviceProxy(')],
          [t('p', '      '), t('t', "'app.acme.todo-app~'")],
          [t('p', '      '), t('t', "+ 'com.example.TodoService'"), t('p', ')')],
          [t('p', '  }')],
          [t('p', '  complete(id: '), t('t', 'string'), t('p', ') {')],
          [t('p', '    '), t('k', 'return'), t('p', ' this.proxy')],
          [t('p', '      .invoke('), t('t', "'complete'"), t('p', ', [id])')],
          [t('p', '  }')],
          [t('p', '}')],
        ],
      },
      {
        file: 'microservices/main/src/TodoService.ts',
        code: [
          [t('d', '> '), t('b', '"push overdue ones to the console"')],
          [],
          [t('c', '// a method returning an Observable')],
          [t('c', '// is a stream, not a response')],
          [t('p', '  watchOverdue(): '), t('t', 'Observable<Todo>'), t('p', ' {')],
          [t('p', '    '), t('k', 'return'), t('p', ' this.overdue$')],
          [t('p', '  }')],
          [],
          [t('c', '// and in the console')],
          [t('p', 'todos.watchOverdue().subscribe({')],
          [t('p', '  next: todo => '), t('b', 'render'), t('p', '(todo),')],
          [t('p', '  error: err => '), t('b', 'toast'), t('p', '(err)')],
          [t('p', '})')],
        ],
      },
    ],
  },
  {
    id: 'ship',
    number: '04',
    title: 'Ship the UI',
    summary: 'React, Vue or plain TS, holding the same repositories your services hold.',
    icon: 'Frontends',
    slides: [
      {
        file: 'web/src/main.ts',
        code: [
          [t('d', '> '), t('b', '"a console: search, list, complete"')],
          [],
          [t('c', '// React, Vue, or plain TS')],
          [t('p', 'Kinotic.'), t('b', 'use'), t('p', '(PersistencePlugin)')],
          [],
          [t('c', '// a browser passes no credentials —')],
          [t('c', '// the OIDC session and the page origin')],
          [t('c', '// resolve the connection')],
          [t('k', 'await'), t('p', ' Kinotic.connect()')],
          [],
          [t('k', 'const'), t('p', ' todos = '), t('k', 'new'), t('p', ' TodoRepository()')],
          [t('k', 'const'), t('p', ' service = '), t('k', 'new'), t('p', ' TodoServiceProxy(')],
          [t('p', '  Kinotic)')],
          [],
          [t('c', '// the same repository class the')],
          [t('c', '// microservice imports')],
        ],
      },
      {
        file: 'web/src/todos.ts',
        code: [
          [t('k', 'const'), t('p', ' page = '), t('k', 'await'), t('p', ' todos.search(q, {')],
          [t('p', '  page: '), t('t', '0'), t('p', ', size: '), t('t', '25'), t('p', ' })')],
          [],
          [t('k', 'for'), t('p', ' ('), t('k', 'const'), t('p', ' todo '), t('k', 'of'), t('p', ' page.content) {')],
          [t('p', '  '), t('k', 'if'), t('p', ' (todo.priority > '), t('t', '3'), t('p', ')')],
          [t('p', '    '), t('k', 'await'), t('p', ' service.complete(todo.id)')],
          [t('p', '}')],
          [],
          [t('d', '$ '), t('b', 'git push')],
          [],
          [t('c', '// Kinotic OS takes it from here')],
          [t('s', '✓ '), t('b', 'Todo '), t('s', 'synced'), t('d', '        // storage + index')],
          [t('s', '✓ '), t('b', 'todo-service '), t('s', 'live')],
          [t('s', '✓ '), t('b', 'todo-console '), t('s', 'deployed')],
          [],
          [t('c', '// no pipeline to configure')],
        ],
      },
    ],
  },
  {
    id: 'hand-back',
    number: '05',
    title: 'Hand it back',
    summary: 'Mark a method an MCP tool and the assistant that built the app can operate it.',
    icon: 'McpTools',
    slides: [
      {
        file: 'microservices/main/src/TodoService.ts',
        code: [
          [t('d', '> '), t('b', '"let my assistant use this too"')],
          [],
          [t('c', '// the service you already have,')],
          [t('c', '// two methods marked as tools')],
          [t('p', '  '), t('a', '@McpTool'), t('p', '({')],
          [t('p', '    title: '), t('t', "'Find Todos'"), t('p', ',')],
          [t('p', '    description: '), t('t', "'Search open todos'"), t('p', ',')],
          [t('p', '    readOnlyHint: '), t('t', 'true')],
          [t('p', '  })')],
          [t('p', '  search(q: '), t('t', 'string'), t('p', ') { ... }')],
          [],
          [t('p', '  '), t('a', '@McpTool'), t('p', '({ title: '), t('t', "'Complete Todo'"), t('p', ' })')],
          [t('p', '  complete(id: '), t('t', 'string'), t('p', ') { ... }')],
          [],
          [t('c', '// the hints tell a host what is safe')],
          [t('c', '// to run unattended')],
        ],
      },
      {
        file: 'claude · todo-app',
        code: [
          [t('c', '// same assistant, now on live data')],
          [t('d', '> '), t('b', '"which pump todos are still open?"')],
          [],
          [t('g', '  TodoService.search')],
          [t('d', '  ↳ 3 results')],
          [],
          [t('d', '> '), t('b', '"complete the two Jane finished"')],
          [],
          [t('g', '  TodoService.complete ×2')],
          [t('s', '  ✓ done')],
          [],
          [t('c', '// you never wrote an endpoint, a')],
          [t('c', '// schema, or an auth check for this')],
        ],
      },
    ],
  },
]

/** How long each slide holds before the walkthrough moves on, in milliseconds. */
const SLIDE_MS = 7000

const stepIndex = ref(0)
const slideIndex = ref(0)
const step = computed(() => steps[stepIndex.value]!)
const slide = computed(() => step.value.slides[slideIndex.value]!)
const tabs = useTemplateRef<HTMLButtonElement[]>('tabs')
const track = useTemplateRef<HTMLElement>('track')

const playing = ref(false)
const onscreen = ref(false)
const attended = ref(false)

// The walkthrough only advances while it is on screen and unattended, so a
// viewer reading one slide is never pulled off it, and an off-screen section
// isn't burning frames.
const advancing = computed(() => playing.value && onscreen.value && !attended.value)

// Pointer or focus on the play control is an instruction to run, so it must not
// register as attention the way the rail and the code pane do. Hence mouseover
// rather than mouseenter: it reports the element actually under the pointer.
function onAttend(event: Event) {
  attended.value = !(event.target as HTMLElement).closest('.api__play')
}

let frame = 0
let previous = 0
let elapsed = 0

/** Writes the dot fill directly, to keep the per-frame progress out of Vue's reactivity. */
function paintProgress() {
  track.value?.style.setProperty('--k-progress', String(elapsed / SLIDE_MS))
}

/** Walks to the next slide of this step, or to the first slide of the next step. */
function advance() {
  if (slideIndex.value < step.value.slides.length - 1) {
    slideIndex.value += 1
  }
  else {
    stepIndex.value = (stepIndex.value + 1) % steps.length
    slideIndex.value = 0
  }
}

function tick(now: number) {
  if (previous) elapsed += now - previous
  previous = now

  if (elapsed >= SLIDE_MS) {
    elapsed = 0
    advance()
  }

  paintProgress()
  frame = requestAnimationFrame(tick)
}

/** Hands control to the viewer, per the ARIA carousel pattern: rotation stops for good. */
function take() {
  elapsed = 0
  playing.value = false
  paintProgress()
}

function selectStep(index: number) {
  stepIndex.value = index
  slideIndex.value = 0
  take()
}

function selectSlide(index: number) {
  slideIndex.value = index
  take()
}

watch(advancing, (on) => {
  if (on) {
    previous = 0
    frame = requestAnimationFrame(tick)
  }
  else {
    cancelAnimationFrame(frame)
    frame = 0
    paintProgress()
  }
})

/** Roving focus across the step list, per the WAI-ARIA tabs pattern. */
function onTabKeydown(event: KeyboardEvent) {
  const last = steps.length - 1
  let next: number
  if (event.key === 'ArrowDown' || event.key === 'ArrowRight') next = stepIndex.value === last ? 0 : stepIndex.value + 1
  else if (event.key === 'ArrowUp' || event.key === 'ArrowLeft') next = stepIndex.value === 0 ? last : stepIndex.value - 1
  else if (event.key === 'Home') next = 0
  else if (event.key === 'End') next = last
  else return

  event.preventDefault()
  selectStep(next)
  tabs.value?.[next]?.focus()
}

const pane = useTemplateRef<HTMLElement>('pane')
let observer: IntersectionObserver | undefined

onMounted(() => {
  playing.value = !window.matchMedia('(prefers-reduced-motion: reduce)').matches

  if (!('IntersectionObserver' in window)) {
    onscreen.value = true
    return
  }

  // Watches the code pane rather than the whole panel: on a phone the panel is
  // taller than the viewport, so a ratio threshold against it could never be met.
  observer = new IntersectionObserver(
    entries => { onscreen.value = entries[0]!.isIntersecting },
    { threshold: 0.5 },
  )
  observer.observe(pane.value!)
})

onBeforeUnmount(() => {
  observer?.disconnect()
  cancelAnimationFrame(frame)
})
</script>

<template>
  <section class="k-section api">
    <div class="api__glow" />
    <div class="k-wrap api__inner">
      <div class="k-eyebrow api__eyebrow" data-reveal>
        <span>&quot;STUPID SIMPLE&quot; API</span>
      </div>
      <h2 class="k-heading api__title" data-reveal>From prompt to production</h2>
      <p class="api__lead" data-reveal>
        You describe the app to Claude, ChatGPT or Grok. Everything below is what it writes for you.
      </p>

      <div
        class="api__panel"
        data-reveal
        @mouseover="onAttend"
        @mouseleave="attended = false"
        @focusin="onAttend"
        @focusout="attended = false"
      >
        <div class="api__list" role="tablist" aria-label="Building a Kinotic app" @keydown="onTabKeydown">
          <button
            v-for="(entry, index) in steps"
            :id="`story-tab-${entry.id}`"
            :key="entry.id"
            ref="tabs"
            type="button"
            role="tab"
            class="api__tab"
            :class="{ 'api__tab--active': index === stepIndex }"
            :aria-selected="index === stepIndex"
            :aria-controls="`story-panel-${entry.id}`"
            :tabindex="index === stepIndex ? 0 : -1"
            @click="selectStep(index)"
          >
            <span class="api__tabicon">
              <KinoticIcon :name="entry.icon" :size="20" />
            </span>
            <span>
              <span class="api__tabtitle">
                <span class="api__tabnum">{{ entry.number }}</span>{{ entry.title }}
              </span>
              <span class="api__tabsummary">{{ entry.summary }}</span>
            </span>
          </button>
        </div>

        <div
          :id="`story-panel-${step.id}`"
          ref="pane"
          class="api__code"
          role="tabpanel"
          :aria-labelledby="`story-tab-${step.id}`"
          tabindex="0"
        >
          <div class="api__codebar">
            <!-- The window dots become this step's examples: one per slide, the
                 active one filling as its dwell time runs down. -->
            <span ref="track" class="api__dots" :class="{ 'api__dots--running': advancing }">
              <button
                v-for="(entry, index) in step.slides"
                :key="entry.file + index"
                type="button"
                :class="{
                  'api__dot--active': index === slideIndex,
                  'api__dot--done': index < slideIndex,
                }"
                :aria-label="`Example ${index + 1} of ${step.slides.length}: ${entry.file}`"
                :aria-current="index === slideIndex"
                @click="selectSlide(index)"
              />
            </span>
            <button
              type="button"
              class="api__play"
              :aria-label="playing ? 'Pause the walkthrough' : 'Play the walkthrough'"
              @click="playing = !playing"
            >
              <svg width="11" height="11" viewBox="0 0 11 11" aria-hidden="true">
                <path v-if="playing" d="M2 1h2.4v9H2zM6.6 1H9v9H6.6z" fill="currentColor" />
                <path v-else d="M2.2 1l7 4.5-7 4.5z" fill="currentColor" />
              </svg>
            </button>
            <span class="api__file">{{ slide.file }}</span>
          </div>
          <pre class="api__pre" :key="`${step.id}-${slideIndex}`"><div v-for="(line, index) in slide.code" :key="index" :style="`--k-row: ${index}`"><span
            v-for="(token, tokenIndex) in line"
            :key="tokenIndex"
            :class="`tok tok--${token.kind}`"
          >{{ token.text }}</span></div></pre>
        </div>
      </div>

      <div class="api__cta" data-reveal>
        <a href="#cta" class="k-btn k-btn--red">Get Started ↗</a>
        <a
          href="https://github.com/kinotic-ai/claude-plugin"
          class="k-btn k-btn--ghost"
          target="_blank"
          rel="noopener"
        >Get the plugin ↗</a>
      </div>
    </div>
  </section>
</template>

<style scoped>
.api {
  position: relative;
  overflow: hidden;
}

.api__glow {
  position: absolute;
  top: 0;
  right: -120px;
  width: 520px;
  height: 380px;
  background: radial-gradient(ellipse, rgba(236, 31, 82, 0.12), transparent 70%);
  filter: blur(10px);
  pointer-events: none;
}

.api__inner {
  position: relative;
}

.api__eyebrow {
  justify-content: center;
  margin-bottom: 18px;
}

.api__title {
  font-size: clamp(29px, 3.6vw, 46px);
  text-align: center;
  margin-bottom: 22px;
}

.api__lead {
  max-width: 720px;
  margin: 0 auto 56px;
  text-align: center;
  font-size: 16px;
  line-height: 1.75;
  color: var(--color-k-muted);
}

.api__panel {
  display: grid;
  grid-template-columns: 5fr 7fr;
  border: 1px solid var(--color-k-border);
  background: var(--color-k-bg);
}

.api__list {
  display: flex;
  flex-direction: column;
  border-right: 1px solid var(--color-k-border);
}

.api__tab {
  flex: 1;
  display: flex;
  gap: 18px;
  padding: 20px 30px;
  text-align: left;
  background: transparent;
  border: none;
  border-bottom: 1px solid var(--color-k-border);
  cursor: pointer;
  transition: background 0.2s ease;
}

.api__tab:last-child {
  border-bottom: none;
}

.api__tab:hover {
  background: rgba(255, 255, 255, 0.025);
}

.api__tab--active {
  background: rgba(40, 254, 180, 0.04);
}

.api__tabicon {
  flex: none;
  width: 44px;
  height: 44px;
  border-radius: 8px;
  border: 1px solid rgba(255, 255, 255, 0.12);
  color: var(--color-k-dim);
  background: var(--color-k-bg-panel);
  display: inline-flex;
  align-items: center;
  justify-content: center;
  transition: border-color 0.2s ease, color 0.2s ease;
}

.api__tab--active .api__tabicon {
  border-color: rgba(40, 254, 180, 0.55);
  color: var(--color-k-mint);
}

.api__tabtitle {
  display: block;
  font-family: var(--font-k-mono);
  font-size: 16.5px;
  color: var(--color-k-text);
  margin-bottom: 6px;
}

.api__tabnum {
  margin-right: 10px;
  font-size: 12px;
  color: var(--color-k-fainter);
  transition: color 0.2s ease;
}

.api__tab--active .api__tabnum {
  color: var(--color-k-mint);
}

.api__tabsummary {
  display: block;
  font-size: 13.5px;
  line-height: 1.6;
  color: var(--color-k-muted);
}

.api__code {
  background: #0A0A0C;
  padding: 26px 34px;
  position: relative;
  min-height: 420px;
}

.api__codebar {
  display: flex;
  align-items: center;
  gap: 14px;
  margin-bottom: 26px;
}

.api__dots {
  display: inline-flex;
  gap: 7px;
}

.api__dots button {
  width: 9px;
  height: 9px;
  padding: 0;
  border: none;
  border-radius: 50%;
  background: #3A3A40;
  cursor: pointer;
  transition: background 0.3s ease;
}

.api__dots button.api__dot--done {
  background: var(--color-k-fainter);
}

/* The active dot fills like a pie chart as its slide's dwell time runs down, from
   the --k-progress the walkthrough timer writes each frame. The inherited
   background transition has to go, or the fill lags the clock it reports. */
.api__dots button.api__dot--active {
  transition: none;
  background:
    conic-gradient(var(--color-k-mint) calc(var(--k-progress, 0) * 360deg), rgba(40, 254, 180, 0.22) 0);
}

.api__dots:not(.api__dots--running) button.api__dot--active {
  background: var(--color-k-mint);
}

.api__play {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 22px;
  height: 22px;
  margin-right: auto;
  padding: 0;
  background: none;
  border: none;
  border-radius: 4px;
  color: var(--color-k-fainter);
  cursor: pointer;
  transition: color 0.2s ease, background 0.2s ease;
}

.api__play:hover {
  color: var(--color-k-text);
  background: rgba(255, 255, 255, 0.06);
}

.api__file {
  font-family: var(--font-k-mono);
  font-size: 11.5px;
  color: var(--color-k-fainter);
}

/* A row carrying no tokens is a deliberate blank line between the code and the
   commentary under it; an empty div would otherwise collapse to no height. */
.api__pre > div:empty {
  height: 1lh;
}

.api__pre {
  margin: 0;
  font-family: var(--font-k-mono);
  font-size: 13px;
  line-height: 2.05;
  color: var(--color-k-body);
  white-space: pre-wrap;
}

/* Re-keyed on every step, so each pane's rows type themselves in top to bottom —
   the assistant writing the file. */
.api__pre > div {
  animation: api-row 0.4s cubic-bezier(0.16, 1, 0.3, 1) backwards;
  animation-delay: calc(var(--k-row) * 45ms);
}

@keyframes api-row {
  from {
    opacity: 0;
    transform: translateX(-6px);
  }
}

.tok--c { color: var(--color-k-fainter); }
.tok--k { color: var(--color-k-mint); }
.tok--p { color: var(--color-k-body); }
.tok--t { color: #EC5C7F; }
.tok--a { color: var(--color-k-mint); }
.tok--g { color: var(--color-k-dim); }
.tok--d { color: var(--color-k-fainter); }
.tok--b { color: var(--color-k-text); }
.tok--s { color: var(--color-k-mint); }

.api__cta {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  gap: 14px;
  margin-top: 56px;
}

@media (max-width: 930px) {
  .api__panel {
    grid-template-columns: 1fr;
  }

  .api__list {
    border-right: none;
    border-bottom: 1px solid var(--color-k-border);
  }
}

@media (max-width: 600px) {
  .api__tab {
    padding: 18px;
  }

  .api__code {
    padding: 20px 16px;
    min-height: 0;
  }

  /* The file paths are long enough that they need the full width, so the name
     wraps onto its own line under the dots rather than sharing theirs. */
  .api__codebar {
    flex-wrap: wrap;
    gap: 12px 14px;
  }

  .api__file {
    width: 100%;
  }

  .api__pre {
    font-size: 11px;
    line-height: 1.95;
  }
}
</style>
