import { type IEntitiesRepository } from '@kinotic-ai/persistence'
import { BaseAppointmentRepository } from './generated/BaseAppointmentRepository.js'

/**
 * Service for interacting with Appointment entities
 * This class was generated by the structures cli
 */
export class AppointmentRepository extends BaseAppointmentRepository {

  constructor(entitiesRepository?: IEntitiesRepository) {
    super(false, entitiesRepository)
  }

}
