import { type IEntitiesRepository } from '@kinotic-ai/persistence'
import { BaseDiagnosisRepository } from './generated/BaseDiagnosisRepository.js'

/**
 * Service for interacting with Diagnosis entities
 * This class was generated by the structures cli
 */
export class DiagnosisRepository extends BaseDiagnosisRepository {

  constructor(entitiesRepository?: IEntitiesRepository) {
    super(false, entitiesRepository)
  }

}
