import { type IEntitiesRepository } from '@kinotic-ai/persistence'
import { BasePatientRepository } from './generated/BasePatientRepository.js'

/**
 * Service for interacting with Patient entities
 * This class was generated by the structures cli
 */
export class PatientRepository extends BasePatientRepository {

  constructor(entitiesRepository?: IEntitiesRepository) {
    super(false, entitiesRepository)
  }

}
