import { IEntitiesService } from '@kinotic-ai/persistence'
import { BasePatientRepository } from './generated/BasePatientRepository.js'

/**
 * Service for interacting with Patient entities
 * This class was generated by the structures cli
 */
export class PatientRepository extends BasePatientRepository {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
