import { IEntitiesService } from '@kinotic-ai/persistence'
import { BasePrescriptionRepository } from './generated/BasePrescriptionRepository.js'

/**
 * Service for interacting with Prescription entities
 * This class was generated by the structures cli
 */
export class PrescriptionRepository extends BasePrescriptionRepository {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
