import { IEntitiesService } from '@kinotic-ai/persistence'
import { BaseProviderRepository } from './generated/BaseProviderRepository.js'

/**
 * Service for interacting with Provider entities
 * This class was generated by the structures cli
 */
export class ProviderRepository extends BaseProviderRepository {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
