import { IEntitiesService } from '@kinotic-ai/persistence'
import { BaseTreatmentRepository } from './generated/BaseTreatmentRepository.js'

/**
 * Service for interacting with Treatment entities
 * This class was generated by the structures cli
 */
export class TreatmentRepository extends BaseTreatmentRepository {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
