import { IEntitiesService } from '@kinotic-ai/persistence'
import { BaseCustomerRepository } from './generated/BaseCustomerRepository.js'

/**
 * Service for interacting with Customer entities
 * This class was generated by the structures cli
 */
export class CustomerRepository extends BaseCustomerRepository {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
