import { IEntitiesService } from '@kinotic-ai/persistence'
import { BaseProductReviewRepository } from './generated/BaseProductReviewRepository.js'

/**
 * Service for interacting with ProductReview entities
 * This class was generated by the structures cli
 */
export class ProductReviewRepository extends BaseProductReviewRepository {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
