import { type IEntitiesRepository } from '@kinotic-ai/persistence'
import { BaseProductRepository } from './generated/BaseProductRepository.js'

/**
 * Service for interacting with Product entities
 * This class was generated by the structures cli
 */
export class ProductRepository extends BaseProductRepository {

  constructor(entitiesRepository?: IEntitiesRepository) {
    super(false, entitiesRepository)
  }

}
