import { IEntitiesService } from '@kinotic-ai/persistence'
import { BasePurchaseRepository } from './generated/BasePurchaseRepository.js'

/**
 * Service for interacting with Purchase entities
 * This class was generated by the structures cli
 */
export class PurchaseRepository extends BasePurchaseRepository {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
