allowBuilds:
  cpu-features: false
  esbuild: true
  protobufjs: false
  ssh2: false
minimumReleaseAgeExclude:
  - '@kinotic-ai/core@3.1.0'
  - '@kinotic-ai/os-api@3.1.0'
  - '@kinotic-ai/persistence@3.1.0'
  - '@kinotic-ai/idl@1.0.10'
