allowBuilds:
  cpu-features: false
  esbuild: true
  protobufjs: false
  ssh2: false
minimumReleaseAgeExclude:
  - '@kinotic-ai/core@4.0.0'
  - '@kinotic-ai/os-api@4.0.0'
  - '@kinotic-ai/persistence@4.0.0'
  - '@kinotic-ai/kinotic-cli@4.0.0'
  - '@kinotic-ai/idl@1.0.10'
