// Domain models
export * from '@/api/model/EntityDefinition'
export * from '@/api/model/NamedQueriesDefinition'
export * from '@/api/model/MigrationDefinition'
export * from '@/api/model/MigrationRequest'
export * from '@/api/model/MigrationResult'
export * from '@/api/model/QueryParameter'
export * from '@/api/model/QueryOptions'
export * from '@/api/model/TenantSpecificId'
export * from '@/api/model/config/CalculatedPropertyConfiguration'
export * from '@/api/model/config/EntityConfiguration'
export * from '@/api/model/config/OverrideConfiguration'
export * from '@/api/model/config/StructuresProjectConfig'
export * from '@/api/model/config/TransformConfiguration'
export * from '@/api/model/insights/DataInsightsComponent'
export * from '@/api/model/insights/InsightProgress'
export * from '@/api/model/insights/InsightRequest'

// Decorators
export * from '@/api/decorators/AutoGeneratedIdDecorator'
export * from '@/api/decorators/DiscriminatorDecorator'
export * from '@/api/decorators/EntityDecorator'
export * from '@/api/decorators/EntityServiceDecorator'
export * from '@/api/decorators/EntityServiceDecoratorsConfig'
export * from '@/api/decorators/EntityServiceDecoratorsDecorator'
export * from '@/api/decorators/EntityType'
export * from '@/api/decorators/EsIndexConfigurationData'
export * from '@/api/decorators/EsIndexConfigurationDecorator'
export * from '@/api/decorators/FlattenedDecorator'
export * from '@/api/decorators/IdDecorator'
export * from '@/api/decorators/MultiTenancyType'
export * from '@/api/decorators/NestedDecorator'
export * from '@/api/decorators/NotIndexedDecorator'
export * from '@/api/decorators/PolicyDecorator'
export * from '@/api/decorators/PrecisionType'
export * from '@/api/decorators/QueryDecorator'
export * from '@/api/decorators/RoleDecorator'
export * from '@/api/decorators/TenantIdDecorator'
export * from '@/api/decorators/TextDecorator'
export * from '@/api/decorators/TimeReferenceDecorator'
export * from '@/api/decorators/VersionDecorator'

// IDL C3Types
export * from '@/api/idl/PageC3Type'
export * from '@/api/idl/PageableC3Type'
export * from '@/api/idl/QueryOptionsC3Type'
export * from '@/api/idl/TenantSelectionC3Type'

// Services
export * from '@/api/IEntityDefinitionService'
export * from '@/api/IEntitiesService'
export * from '@/api/IAdminEntitiesService'
export * from '@/api/IEntityService'
export * from '@/api/IAdminEntityService'
export * from '@/api/INamedQueriesService'
export * from '@/api/IMigrationService'
export * from '@/api/IDataInsightsService'

// Plugin
export * from '@/api/PersistencePlugin'

// Re-export Kinotic core so consumers only need one import
export { Kinotic, KinoticSingleton, type IKinotic, type KinoticPlugin } from '@kinotic-ai/core'

import type { IPersistenceExtension } from '@/api/PersistencePlugin'

declare module '@kinotic-ai/core' {
    interface KinoticSingleton extends IPersistenceExtension {}
}
