name: Build and Deploy Kinotic Website

on:
  push:
    branches:
      - develop
    paths:
      - 'website/**'

jobs:
  build_and_deploy_website:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: |
          cd website
          bun install

      - name: Build site
        run: |
          cd website
          bun run generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/.output/public
          publish_branch: gh-pages
          keep_files: false
